README.md
Also, add qemu equivalent command for iso install
Signed-off-by: Sinny Kumari <sinny@redhat.com>
=> Update README with F30 artifacts for ISO/PXE based install

coreos-installer
This is helpful to verify what the installer actually did.
=> installer: add some more logging statements

README.md
- Update for combined BIOS/UEFI images
- Update for separate PXE installer image
- Use current image filenames
- Point to download page
- Make separate PXE and ISO sections
- Wording cleanups
=> README: general cleanups

coreos-installer
=> Fix some error spew

coreos-iso-embed-ignition
Part of https://github.com/coreos/fedora-coreos-config/pull/171.
=> Add tool to embed Ignition config in live ISO image

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/release-checklist.md, doc/development.md
=> Add issue templates

src/blockdev.rs, src/source.rs
=> Avoid some redundant unwraps

src/blockdev.rs
Spell out the implications of an `EINVAL` or `EBUSY`.
=> Improve error messages when rereading partition table

src/verify.rs
After importing GPG keys, extract their key IDs and explicitly mark them trusted.  Avoids warning message on verify:
gpg: WARNING: Using untrusted key!
=> verify: Explicitly trust imported keys

.github/ISSUE_TEMPLATE/release-checklist.md
This fixes a minor typo in release-checklist.
=> docs: fix typo in release-checklist

README.md
This is a minor README enhancement, adding badges and links to container
repository and crates.io binary.
=> README: add badges and links

Cargo.toml
See individual commit messages.
=> A few more Cargo.toml fixups for newer `cargo-release`

src/install.rs
Otherwise it's a painful experience to fail the install after having
already downloaded the image and written it to disk because of a typo in
the filename.
=> install: check for Ignition config upfront

src/download.rs
If we try to use CR to overwrite the previous progress message, and our stderr is being read by another program such as journald, we're likely to cause confusion.  Just write regular log lines if stderr is not a tty.
Fixes #120.
=> download: simplify progress reporting if stderr is not a tty

src/source.rs
This adds a very large timeout (4 hours) to all HTTP requests, as they
currently default to none.
It is meant to almost never trigger, except under pathological network
conditions. In such cases, it should help detecting issues by explicitly
erroring out instead of hanging forever.
=> source: add an upper bound timeout to HTTP requests

Cargo.lock, Cargo.toml, src/blockdev.rs, src/verify.rs
=> Switch from deprecated tempdir crate to tempfile

src/source.rs
This tweaks the signature fetching logic, so that it log-and-continues
on any kind of errors (e.g. timeouts or broken redirects).
This is mostly useful for the "insecure" mode, where remote images
can be consumed even without a corresponding signature.
In "normal" mode, such case will instead result in an hard-failure
when trying to validate the (missing) signature.
Additionally, this prints more error details on non-OK HTTP responses.
Ref: coreos/fedora-coreos-tracker#402
=> source: keep going on signature-fetching errors

src/blockdev.rs
=> blockdev: get path directly from lsblk output

README.md
Now it matches the `virt-install` example
=> README: adjust RAM for qemu example

src/cmdline.rs
Change the default `install` behaviour to always install from the osmet
files if present. In live CoreOS systems that should always be the case.
In other contexts, like containers, we automatically default back to
online installs as before.
Patch best viewed with whitespaces ignored.
=> install: default to offline installs via osmet

src/blockdev.rs
Prep for some RHCOS+osmet work; the devmapper device doesn't
have the same sysfs attrs.
=> blockdev: Lower the API to query size to BlkDev

src/blockdev.rs, src/install.rs, src/osmet/mod.rs
blockdev still has a number of rough edges, but hopefully this is incrementally better.
=> blockdev: some refactoring

.github/ISSUE_TEMPLATE/release-checklist.md
@lucab, thoughts on the second commit?
=> release-checklist: some cleanups

.travis.yml
=> ci: bump toolchains

src/blockdev.rs, src/lib.rs, src/s390x/dasd.rs, src/util.rs
Split out of https://github.com/coreos/coreos-installer/pull/304.
See individual commit messages.
=> Prep patches for `rdcore rootmap`

.cci.jenkinsfile
Requires https://github.com/coreos/coreos-assembler/pull/1646
=> ci: add pxe-offline-install testiso scenario

.github/workflows/rust.yml
This adds a new workflow on GitHub with a few jobs for Rust testing.
=> github/workflows: add Rust testing

.github/workflows/rust.yml, src/blockdev.rs
This contains minor fixes related to formatting and workflows definition.
=> ci: misc fixes

.github/workflows/containers.yml
This adds a new workflow building the fedora-based container image.
=> workflows: add containers job

src/s390x/dasd.rs
`fdasd -p` also needs `udevadm settle` to avoid possible race condition.
This a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1900699
=> s390x: trigger 'udevadm settle' after checking DASD's validity

docs/osmet.md
This was requested a few times.
Closes: #463
=> docs: document how osmet works

src/live.rs
When given the `-o -` option, coreos-installer will stream the resulting
ISO to stdout.
Fixes #382
=> iso: stream iso ignition embed to stdout

src/live.rs, tests/test-iso-kargs.sh
When given the `-o -` option, coreos-installer will stream the resulting ISO to stdout.
Fixes #479
Requires #480
=> iso: stream iso kargs {modify|reset} to stdout

src/bin/rdcore/cmdline.rs, src/bin/rdcore/kargs.rs, src/bin/rdcore/rootmap.rs, src/install.rs, src/live.rs
See individual commit messages.
For https://github.com/coreos/ignition/issues/1168.
Requires: https://github.com/coreos/coreos-installer/pull/497
=> rdcore/kargs: add --should-exist and --should-not-exist

Cargo.toml
Fixes https://github.com/coreos/coreos-installer/pull/450.
=> cargo: allow tempfile 3.1

src/blockdev.rs
If there are no saved-partition filters, we can skip reading the on-disk GPT, since we're going to completely replace it.  This prevents us from failing the install if the primary and backup GPT are both corrupt (e.g. a CRC check fails) and partition saving is not enabled.
Fixes #444.
=> blockdev: ignore corrupt GPT in SavedPartitions without filters

Dockerfile
=> Dockerfile: update to F34

scripts/coreos-installer-service
xref: https://github.com/coreos/fedora-coreos-config/pull/1045
=> add coreos.force_persist_ip to list of persisted dracut args

src/blockdev.rs, src/cmdline.rs, src/install.rs, src/s390x/dasd.rs
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1960485
=> s390x: add support for virtio dasds

docs/cmd/iso.md
Document additions from https://github.com/coreos/coreos-installer/pull/341
As far as I could figure out, this is the only undocumented option right now:
Fixes: https://github.com/coreos/coreos-installer/issues/568
=> docs: Add iso kargs modify/reset/show

dracut/50rdcore/module-setup.sh, src/bin/rdcore/kargs.rs, src/bin/rdcore/rootmap.rs, src/install.rs, src/s390x/mod.rs, src/s390x/zipl.rs
Otherwise the changed kargs won't take effect.
=> rdcore/kargs: call `zipl` on s390x after editing BLS

Cargo.lock, Cargo.toml, src/bin/rdcore/cmdline.rs, src/bin/rdcore/kargs.rs, src/bin/rdcore/main.rs, src/bin/rdcore/rootmap.rs, src/cmdline.rs, src/download.rs, src/install.rs, src/io.rs, src/live.rs, src/main.rs, src/osmet/file.rs, src/source.rs, tests/help.sh
Preparatory to #124, and also a nice cleanup.
=> cmdline: switch to structopt

src/download.rs, src/io.rs, src/osmet/io_helpers.rs, src/osmet/mod.rs, src/osmet/unpacker.rs
These were split out of https://github.com/coreos/coreos-installer/pull/559. See individual commits.
=> Prep patches for minimal ISO work

src/download.rs
=> download: give reader wrappers ownership of the inner reader

tests/help.sh
Avoid the need to manually update the test when adding subcommands.
=> tests/help: autodetect subcommands from help text

Dockerfile
xref https://github.com/coreos/fedora-coreos-tracker/issues/884
=> Dockerfile: switch to Fedora 35

src/bin/rdcore/cmdline.rs, src/bin/rdcore/unique_fs.rs, src/blockdev.rs, src/install.rs
This was made to mitigate https://github.com/coreos/fedora-coreos-tracker/issues/976
=> rdcore/installer: warn user when system has several boot partitions 

src/bin/rdcore/kargs.rs, src/bin/rdcore/rootmap.rs, src/install.rs, src/io/bls.rs, src/io/mod.rs, src/live.rs, src/s390x/zipl.rs
They take multiple arguments of the same type, and the argument order isn't obvious.
=> Replace `modify_kargs` and `bls_entry_options_delete_and_append_kargs` with builder struct

.github/ISSUE_TEMPLATE/release-checklist.md, Cargo.toml
See individual commits.
cc @lucab
=> Release process updates

src/miniso.rs
Empty files can be placed anywhere, even in the middle of another file, which can cause table validation to fail.  But they also don't require us to do anything, so just filter them out of the table.  For bookkeeping, continue counting them as a success.
We don't currently have any empty files in the CoreOS ISO; discovered this while making a test fixture.
=> miniso: fix table validation failure on empty files

src/blockdev.rs
There have been no complaints about the mount namespace support, so drop the override.
Fixes https://github.com/coreos/coreos-installer/issues/557.
=> blockdev: drop support for `COREOS_INSTALLER_NO_MOUNT_NAMESPACE`

src/blockdev.rs
Avoid unnecessary retry delays while checking for extra boot partitions after install.
fixes https://github.com/coreos/coreos-installer/issues/746
=> blockdev: add 'retry' flag to reread_partition_table 

Makefile
When testing in debug mode, we don't want to copy the full ~180M
`rdcore` binary in the initramfs to avoid taking too much space. In
release mode, we do want it because it gets split into the debuginfo
package anyway.
Tweak things so that by default in debug mode, we strip the binary. Do
it in a separate step instead of using `install --strip` because we only
want to strip DWARF info, but by default the full symbol table is
stripped and there's no way to customize it.
This will have an effect on backtraces in case of crashes/panics.
Function names will still be printed, but filenames and line numbers
will be missing.
=> Makefile: strip `rdcore` DWARF in debug mode

docs/release-notes.md, src/s390x/zipl.rs
=> Minor follow-up tweaks related to recent s390x PRs

Dockerfile, docs/release-notes.md
https://github.com/coreos/fedora-coreos-tracker/issues/1223
=> dockerfile: rebase to f37 from f36

scripts/coreos-installer-service, tests/images.sh, tests/images/customize.sh
They look benign but likely need careful review.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1989551
=> *: ShellCheck fixes

ci/shellcheck
Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@71058122bf8a1256ef655f1b5218e49b977b7660.
=> Sync repo templates ⚙

Cargo.lock, docs/release-notes.md
https://github.com/coreos/coreos-installer/issues/1358
=> Pre release 0.20.0

Dockerfile, docs/release-notes.md
https://github.com/coreos/fedora-coreos-tracker/issues/1490#issuecomment-1938656032
=> Dockerfile: rebase from f38 to f39

Dockerfile, docs/release-notes.md
https://github.com/coreos/fedora-coreos-tracker/issues/1674
=> Dockerfile: rebase from f39 to f40

Cargo.lock, docs/release-notes.md
pre-release for https://github.com/coreos/coreos-installer/issues/1488
=> Pre release 0.22.0

Cargo.lock, docs/release-notes.md
https://github.com/coreos/coreos-installer/issues/1495
=> Pre release 0.22.1

Dockerfile, docs/release-notes.md
See: https://github.com/coreos/fedora-coreos-tracker/issues/1695
=> dockerfile: update to `fedora:41`

.cci.jenkinsfile, .github/workflows/rust.yml, tests/images/customize.sh, tests/images/dev-show-iso.sh, tests/images/iso-extract-pxe.sh
These can now be built in a single invocation so let's do that.
=> .cci.jenkinsfile: switch to `cosa osbuild`

Dockerfile, docs/release-notes.md
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1851
=> dockerfile: update to fedora:42
