README.md

This will help people who are trying to use Fedora CoreOS on
bare metal understand how to use the installer to perform
the installation on those nodes.

README: add instructions for using installer on FCOS

---

README.md

Guidance is:
* Use "Red Hat Enterprise Linux" the first time in readme
* Use RHCOS thereafter
* "RHEL CoreOS" is not a thing

Using proper RHCOS name

---

README.md

Adds the line `version = 29` to the `.treeinfo` file declaration.
Without this the `virt-install` will fail with `No option 'version' in
section: 'general'`.

README: fix .treeinfo contents

---

coreos-installer
dracut/30coreos-installer/parse-coreos.sh

Adds support for persisting `ip=` kernel command-line flags from the
installer initramfs to the firstboot initramfs via creating an
`ignition.firstboot` file that can be sourced on the boot partition of
the installed image.
Closes #17

*: persist ip= kcmdline opts to firstboot initramfs

---

dracut/30coreos-installer/parse-coreos.sh

This was causing bash to try to run a command called
`yes` when `coreos.inst=yes` was passed as a karg
and the following error would show up on screen:
```
dracut-cmdline[272]: //lib/dracut/hooks/cmdline/90-parse-coreos.sh: line 46: yes: command not found
dracut-cmdline[272]: //lib/dracut/hooks/cmdline/90-parse-coreos.sh: line 46: yes: command not found
```

dracut: fix logic error in parse-coreos.sh

---

coreos-installer

Adds `-L` to all `curl` calls to honor redirects.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1709247

coreos-installer: Honor redirects via curl

---

coreos-installer
dracut/30coreos-installer/coreos-installer.service
dracut/30coreos-installer/module-setup.sh
dracut/99emergency-failure/failure.sh
dracut/99emergency-failure/module-setup.sh

Switches to `echo "" >&2` and updates the `StandardOutput` of the
`coreos-installer.service` to `kmsg+console`. This makes the installer
be non-interactive. Later patches will drop into a shell in the
initramfs if all required parameters are not given.

*: drop dialog

---

dracut/30coreos-installer/module-setup.sh

With #16 we no longer need `chvt`, `lsblk` or `tee`.

30coreos-installer: drop unused inst_modules

---

coreos-installer

This will skip the empty space in the filesystems, and will
rather dramatically speed up the install.
Not really necessary after
https://github.com/coreos/coreos-assembler/pull/332
but doesn't conflict either.

Use `dd conv=sparse`

---

coreos-installer

Adds an additional check for the exit status of the curl call that does
the image download.
Closes #29

coreos-installer: add check for image download exit status

---

README.md
coreos-installer
dracut/30coreos-installer/coreos-installer.service
dracut/30coreos-installer/module-setup.sh
dracut/30coreos-installer/parse-coreos.sh

This PR contains various fixups that were found while testing out the CLI invocation
of coreos-installer. Probably most effective to review each commit individually.
- f897ff0 o README: add notes for CLI invocation         
- 3870e93 o coreos-installer: clear the trap handler after umount
- 4bc7da9 o coreos-installer: move reboot logic to dracut service
- efe979d o coreos-installer: make sure we run as root
- 666303d o coreos-installer: verify boot partition device
- 520ff67 o coreos-installer: make new mount_boot_partition function
- 4bc70c3 o dracut: alphabetical sort of dracut dependencies

various CLI invocation fixups

---

coreos-installer

Since we use the installer for more than just Fedora let's not
mention it specifically.

coreos-installer: remove 'Fedora' from help text.

---

coreos-installer

enable `pipefail` around `zcat | dd`
Closes #24

coreos-installer: enable `pipefail` around `zcat | dd`

---

dracut/30coreos-installer/module-setup.sh

`zcat` is just a thin shell wrapper around `gzip`. So we need to
explicitly add that to the initrd as well.

module-setup.sh: Explicitly add gzip

---

dracut/30coreos-installer/parse-coreos.sh

Some users may want to disable IPv6 as part of firstboot.  This was
noticed in https://bugzilla.redhat.com/show_bug.cgi?id=1715205

parse-coreos:  persist ipv6.disable

---

README.md

Fix all references to the old builds listing and point to the release
browser instead. Fix all references to split uefi/bios images since they
are now unified.
depends lightly on https://github.com/jlebon/fedora-coreos-browser/pull/1

readme: fix stale links and instructions

---

coreos-installer
dracut/30coreos-installer/module-setup.sh

This change checks magic bytes inside the header of compressed image files.
`gzip` compressed files are checked first 2 bytes while 6 bytes for `xz`
compressed files.

Add support to xz-compressed images

---

dracut/30coreos-installer/parse-coreos.sh

default rd.net.timeout.carrier is 5 seconds. in our dell hardware servers the network cards take a bit longer to come up and this causes the installation to hang forever.
the rd.net.timeout.carrier parameter can be provided during the installation of coreos. unfortunately the parameter is not passed on to the first boot after the installation. 
the pull request add the parameter to the list of params that are passed on.
alternatively the default value could be increased. probably it also would be good if all parameters are passed on to the first boot after the installation.

add rd.net.timeout.carrier parameter to list of kernel opts for first boot

---

README.md
coreos-installer
dracut/30coreos-installer/parse-coreos.sh

Adds a command line option that reads ignition.platform.id from user
and applys / overwrites it in BLS.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/191
Signed-off-by: Zonggen (Allen) Bai, abai@redhat.com

coreos-installer: Use sed to overwrite ignition.platform.id in BLS

---

coreos-installer

This reverts commit 33ba62ef154c32b6e5d8b4278e7f56180a31d8c5.
As bgilbert points out in
https://github.com/coreos/coreos-installer/pull/20#issuecomment-547561379
> This isn't safe. The image might contain zeroed blocks for reasons other
> than unallocated space, and if the target disk already has data on it,
> we'll write a corrupt image to disk.

Revert "Use `dd conv=sparse`"

---

src/blockdev.rs
src/main.rs

- If the output path is not a block device, produce an error message that doesn't talk about typewriters
- Issue discard request for entire output device before writing to it, and also after a failure
- Minor cleanups

Block device handling improvements

---

src/cmdline.rs
src/download.rs
src/install.rs
src/main.rs
src/source.rs
src/verify.rs

Features:
- Downloads an image from FCOS stream metadata or from a manually-specified URL
- Requires GPG signatures unless `--insecure` specified
- Avoids redownload if it can verify an existing GPG signature
- Optionally decompresses the downloaded image
- Can download arbitrary FCOS (stream, architecture, platform, format) tuple
- Automatically downloads all artifacts from multi-artifact images
Requires https://github.com/coreos/coreos-installer/pull/77.

Add download subcommand

---

src/cmdline.rs
src/main.rs
src/source.rs

Allow users to examine the architectures, platforms, and  formats available within FCOS stream metadata.  Don't support listing artifacts within a format, since the `download` subcommand will download all of them.
Unlike #79, this version generates a table with all arch/platform/format tuples, and doesn't provide arguments for filtering.  Sample output:
```
$ ./coreos-installer list-stream  -s testing
Architecture  Platform   Format
x86_64        aws        vmdk.xz
x86_64        metal      installer-pxe
x86_64        metal      installer.iso
x86_64        metal      iso
x86_64        metal      pxe
x86_64        metal      raw.xz
x86_64        openstack  qcow2.xz
x86_64        qemu       qcow2.xz
x86_64        vmware     ova
```
Requires #78.

Add list-stream subcommand, tabular version

---

doc/iso-embed-ignition.md

This adds a docs item, mostly meant for other developers, describing
what is the technical contract governing ISO embed area.

docs: add technical details about iso-embedding

---

dracut/30coreos-installer/parse-coreos.sh

Only allowing single key-value correspondence would cause problems when customers
want to put more than 1 DNS server in their production instances. Previously only
the last value would be picked if multiple values under the same key are passed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1763341
Signed-off-by: Allen Bai <abai@redhat.com>

dracut/parse-coreos.sh: allow multiple networking karg values under same key

---

src/verify.rs

Older gpg, such as 2.0.22 in CentOS 7.6, doesn't support the TOFU trust model.  Switch to `always`, which makes older hosts work at the cost of a worse spurious warning.  Old verification text:
```
gpg: Signature made Mon 14 Oct 2019 11:59:16 PM EDT
gpg:                using RSA key EF3C111FCFC659B9
gpg: Good signature from "Fedora (30) <fedora-30-primary@fedoraproject.org>" [full]
gpg: fedora-30-primary@fedoraproject.org: Verified 1 signatures in the past
0 seconds.  Encrypted 0 messages.
```
New verification text:
```
gpg: Signature made Mon 14 Oct 2019 11:59:16 PM EDT
gpg:                using RSA key EF3C111FCFC659B9
gpg: Good signature from "Fedora (30) <fedora-30-primary@fedoraproject.org>" [unknown]
gpg: WARNING: Using untrusted key!
```
The `WARNING` line is intentional on the …

verify: Switch to `always` trust model

---

Cargo.lock
Cargo.toml
src/blockdev.rs

The CentOS 7.6 `lsblk` doesn't support `--json` or the PATH key.  Switch to `--pairs`, and form the device path from `NAME`.

Fix mounting boot device on CentOS 7.6

---

src/main.rs

This is a minor cosmetic fix, getting rid of wildcard imports in main.
The goal here is to make codebase more immediate to read/navigate
and to avoid future spurious name conflicts.

main: get rid of wildcard imports

---

coreos-installer

Moving forward, both FCOS and RHCOS use the same partitioning scheme
Only 4.2 RHCOS uses anaconda where the root parition index is 2. So,
making that an exception

Change Root partition index to 4 by default for DASD installs

---

README.md
systemd/coreos-installer-service

Pending the discussion in #124 let's minimize the number of kargs
for now. coreos.inst.stream_base_url was identified as one that
wasn't absolutely necessary.
This is a followup to #119 to address this discussion:
https://github.com/coreos/coreos-installer/pull/119#discussion_r363791801

Remove coreos.inst.stream_base_url karg

---

systemd/coreos-installer-service
systemd/coreos-installer.service

Previously you could prematurely continue into /usr/bin/coreos-installer
before DNS was up. This commit improves network checking such that DNS
is checked (if needed) before continuing.

systemd: remove rudimentary network checking code; depend on NetworkManager

---

Cargo.toml

Support for this was removed upstream [1] and now I get can error
like this when running cargo-release:
```
Fatal: Invalid TOML file format: unknown field `upload-doc`
```
[1] https://github.com/sunng87/cargo-release/commit/739d746

Cargo.toml: remove package.metadata.release.upload-doc option

---

Cargo.lock
Cargo.toml

Benjamin Gilbert <bgilbert@redhat.com> (2):
da95cd2 dracut: drop dracut modules
6dd597a systemd: add scripts and systemd units for running at boot
Colin Walters <walters@verbum.org> (1):
35b41f9 systemd: Add After=network-online.target
Dusty Mabe <dusty@dustymabe.com> (16):
cdb76d0 systemd: service: fix calls to get commandline arg values
8841fb8 systemd: generator: rename cmdline_arg() to karg()
7e115d0 systemd: installer: indicate we want the network
2d61ae3 systemd: reboot service: fix path to systemctl
cb6dc61 systemd: generator: mv reboot flag file creation to generator
87c8c31 systemd: service: Make reboot service run after installer
1dffdf9 systemd: services: log more to the console
352af2d systemd: use OnFailureJobMode=replace-irreversibly
dd3aa1c systemd: add …

Release 0.1.2

---

systemd/coreos-installer-service

This adds some retries to curl when downloading Ignition config.
It should give us some room for resiliency in case of transient
network hiccups.
Proactive measure, this has not yet been observed/reported as a
direct cause of failures in the wild.
Related: https://github.com/coreos/coreos-installer/pull/127

service: add some retries when downloading

---

src/iso.rs

This adds a basic smoke test to check that reading/writing logic for
embedded Ignition config can roundtrip without issues.

tests/iso: test Ignition cpio read/write roundtrip

---

.travis.yml
Cargo.lock
Cargo.toml
src/errors.rs
src/source.rs

This updates to `reqwest` 0.10. The default API is now async, but I simply updated and sticked to the blocking API which is good enough for our usecases.
Closes: https://github.com/coreos/coreos-installer/pull/139

cargo: update to reqwest 0.10 and new API

---

src/blockdev.rs
src/install.rs

In 7b89735c0906 we started issuing block discard requests over the destination disk, before install and after install failure, as a courtesy to SSD wear levelers and LVM thin pools.  However, this assumes that the entire disk is ours to discard.  Users might want to reprovision an existing machine without disturbing a data partition they've created on the boot disk; their Ignition config can then recreate the data partition in the same place and reuse the filesystem inside.
Discard the discard functionality for now.  We shouldn't require users to explicitly specify `--dont-delete-my-data`, and the semantics of `--delete-my-data` (under whatever name, e.g. `--discard-device`) would be difficult to explain relative to the value they provide.  Users can still run `blkdiscard(8)` before …

Stop discarding disk contents

---

src/cmdline.rs

We'll eventually want to support URLs, and it's safer for the user to specify the argument type rather than us trying to guess.  For consistency with `--image-file`/`--image-url`, rename `--ignition` to `--ignition-file`.  Continue accepting `--ignition` for now as an undocumented alias.
Toward https://github.com/coreos/coreos-installer/issues/118#issuecomment-585572952.
cc @jlebon @dustymabe

install: Rename --ignition to --ignition-file

---

Cargo.lock
Cargo.toml

This drops strict requirements on micro versions in order to make
packaging efforts more relaxed.

cargo: relax dependencies micro versions

---

.cci.jenkinsfile

Part of https://github.com/coreos/fedora-coreos-tracker/issues/263
This makes use of the new `kola testiso` command too.

ci: Add a CoreOS CI test

---

src/source.rs

This simplifies the logic for fetching signature content, dropping
an unnecessary match statement.
Followup-To: https://github.com/coreos/coreos-installer/pull/177#discussion_r387240702

source: rework signature fetching

---

src/cmdline.rs
src/install.rs

If `--preserve-on-error` is specified, don't clear the destination partition table on error, as a debugging aid.
For https://github.com/coreos/coreos-installer/issues/165#issuecomment-588380848.

install: Add option to skip clearing partition table on error

---

src/download.rs

I think using that API call is a bit of a code smell; it isn't
*wrong* but I think it's better to use matching like `if let Some(x)`.
Among other things it avoids an `unwrap()` call which is *definitely*
a code smell.  It's harder for the compiler to optimize out the
`unwrap()` too since it has to reason about the `is_some()` logic.
If agreed I'll change a few other places like this too.

download: Avoid using `is_some()`

---

src/blockdev.rs
src/install.rs

Split out of https://github.com/coreos/coreos-installer/pull/187. See individual commit messages.

blockdev: preparatory patches for osmet

---

Cargo.lock
Cargo.toml

Major changes:
- Rename `--ignition` to `--ignition-file`.  `--ignition` is still accepted for compatibility.
- Don't discard disk contents before installing, so we don't delete data partitions when reprovisioning
- Add `--preserve-on-error` debug option to skip clearing partition table on error
Minor changes:
- Fail install early if image sector size doesn't match destination
- Ensure specified Ignition config exists before starting install
- Improve error message when mounting `/boot` if no partitions found
- Ignore HTTP errors on signature fetch if `--insecure` is specified
- Simplify download progress reporting if stderr is not a tty
- Retry when downloading `coreos.inst.ignition_url`
- Add upper-bound timeout to HTTP requests

Release 0.1.3

---

README.md

Reorder the "how to get/use" instructions to demote "via Fedora RPM"
to below "via container".  And also the "on other editions" verbiage
was wrong, because "other editions" include e.g. Silverblue and IoT
which don't use `dnf` for the root filesystem either.
While we're here, note that `dnf install coreos-installer`
*also* works in a `--privileged` container - don't need to mutate
your host's rootfs.
Move "install with cargo" above "build from source" too.
Finally, add a note that older RHCOS uses the `legacy` branch
so people are hopefully less confused why it's different.

README.md: Reorder, and note RHCOS has legacy

---

.cci.jenkinsfile

The current invocation no longer works now that `--cosa-build` was
renamed to just `--build` (in hindsight, I should've probably kept
`--cosa-build` for a bit as an alias).
Anyway, we can drop that argument completely now actually. So let's do
that!

ci: fix `kola testiso` invocation

---

.cci.jenkinsfile
src/blockdev.rs
src/cmdline.rs
src/source.rs

Detect the sector size of the target device, then select the right
format from the stream metadata based on that.
Closes: #201

install: use 4k image when when targeting 4k drives

---

Cargo.lock

Fixes repeated reads of /proc/cpuinfo in debug builds: https://github.com/tokio-rs/tokio/pull/2238

cargo: cargo update

---

src/cmdline.rs
src/install.rs

This will allow us to copy in networking configuration from a specified
location into a predetermined directory inside of `/boot/` of the
installed system (which follows the path of other postprocess steps).
Having this mechanism will allow for a user to interactively configure
networking in the Live ISO environment via `nmtui` and then have those
settings propagate forward into the installed system.
After the files are copied into the directory within `/boot/` a systemd
unit from the initramfs will pick them up on firstboot and propagate
them into the appropriate locations.
Fixes: https://github.com/coreos/coreos-installer/issues/205

install: add --copy-network and --network-dir options

---

Cargo.lock
Cargo.toml
src/cmdline.rs
src/errors.rs
src/install.rs

This adds a new `install --ignition-hash` codepath, in order to
support digesting and validating the hash of the Ignition
configuration before installing to disk.
The command-line parser follows the specification of
`ignition.config.verification.hash` (i.e. `<type>-<value>` format).
Currently the only kind supported is `sha512-<DIGEST>`.
Closes: https://github.com/coreos/coreos-installer/issues/142

install: support checking Ignition config hash

---

systemd/coreos-installer-generator

This is no longer needed since we changed all of Fedora CoreOS to
set SYSTEMD_SULOGIN_FORCE=1 for emergency.service in
https://github.com/coreos/fedora-coreos-config/commit/eb74f2ea3e9b453902315539e4f327481162c4f8

systemd: remove SYSTEMD_SULOGIN_FORCE override for emergency.service

---

.cci.jenkinsfile

This is done in the RHCOS pipeline and will be done soon in FCOS
https://github.com/coreos/fedora-coreos-pipeline/pull/218
Also switch to explicit scenario list as another workaround
for https://github.com/coreos/coreos-assembler/pull/1365

ci: Compress images once, use explicit scenario list

---

src/install.rs

In another code review [1] we agreed to make the name of the directory
more generic.
[1] https://github.com/coreos/fedora-coreos-config/pull/346#discussion_r409640904

install: change /boot/ directory for --copy-network

---

Makefile

Same rationale as https://github.com/coreos/ignition-dracut/pull/106
See https://github.com/cgwalters/build-api
With this for example, we can just have the RHEL spec file do
`make install DESTDIR=$RPM_BUILD_ROOT` just like everything else;
helping to ensure that as much logic as possible remains upstream.

build: Add a Makefile

---

.cci.jenkinsfile

We were doing `cosa build metal` instead of `cosa buildextend-metal`.
And since `fcosBuild` itself already builds a qemu image, we were
essentially doing `create_disk.sh` twice.
Instead, just make the initial `fcosBuild` only build the metal image
since we don't need the QEMU image for our tests. And also skip the
regular kola tests since those don't really test coreos-installer
anyway (and they'd need the QEMU image).

ci: fix building metal image

---

coreos-installer

User may specify `dev/by-path/name` as `coreos.inst.install_dev`,
but on s390x with DASD this breaks the installation.

legacy: resolve symlinks for DEST_DEV

---

Makefile
dracut/30coreos-installer/coreos-installer-generator
dracut/30coreos-installer/coreos-installer.service
dracut/30coreos-installer/module-setup.sh
dracut/30coreos-installer/parse-coreos.sh

For https://github.com/openshift/enhancements/pull/210 I think
we will need at least some transitional period where RHCOS
ships both.  Even ignoring customers, the way our CI works
strongly encourages "ratcheting" changes in a compatible way,
i.e.:
- Introduce new thing, ship it
- Port consumers to new thing
- Remove old thing
And honestly I think this is a good model, because it forces
us to experience some of the pain that customers might feel here.
The basic idea here is:
- Install as `/usr/libexec/coreos-installer.legacy` so there's
no chance of conflict with the real one
- Test for the presence of the "stamp file' we drop in our live initramfs
so we know to defer to the real root's coreos-installer
This would be even more robust if we changed coreos-assembler
to inject an explicit …

 Install as coreos-installer.legacy

---

.cci.jenkinsfile
Cargo.lock
Cargo.toml
src/blockdev.rs
src/cmdline.rs
src/errors.rs
src/install.rs
src/main.rs
src/osmet/fiemap.rs
src/osmet/file.rs
src/osmet/io_helpers.rs
src/osmet/mod.rs
src/osmet/unpacker.rs
src/source.rs

Introduce a new `osmet` command with two primary subcommands: `pack` and
`unpack`. Together, these allow offline bare metal installation of
CoreOS images while only slightly increasing the size of the initramfs.
The `pack` subcommand takes as input a block device of a CoreOS metal
image and the expected checksum to match. It mounts the root partition
from that device and generates a smaller version of the metal image
itself with the OSTree objects "punched out" (this is called the
"punched image" in the code). The command outputs this smaller version
as well as a lookup table of where the OSTree objects belonged into an
"osmet" binary file.
The `unpack` subcommand takes as input an osmet binary file and a path
to an OSTree repo and reconstrust the metal image, bit for bit. This
command is …

osmet: efficient packing/unpacking of CoreOS metal images

---

systemd/coreos-installer-service

This commit fixes two issues with network karg parsing. First,
there are some arguments that can be provided more than once (like
ip=). Second, there are arguments that are boolean args that don't
require a value, which aren't currently getting parsed correctly.
Fixes: https://github.com/coreos/coreos-installer/issues/156
Fixes: https://github.com/coreos/coreos-installer/issues/227

systemd: coreos-installer-service: fix network karg parsing

---

systemd/coreos-installer-generator

Outputting stdout and stderr to /dev/kmsg is the only option for
logging for generators for now. Let's start using it so we can at
least get some messages if we ever have problems with one of our
generators.

systemd: add logging to systemd generator

---

Cargo.lock
Cargo.toml

Major changes:
- By default, install from an offline image shipped with the running system, if available
- When installing from a Fedora CoreOS stream, automatically select 4Kn image if needed
- Add `--copy-network` and `--network-dir` to copy network configs from the running system
- Add `--ignition-hash` to verify the hash of the specified Ignition config
Minor changes:
- Fix `coreos.inst` forwarding of repeated network kargs
- Fix `coreos.inst` forwarding of network kargs without a value
- Get block device path from `lsblk` rather than constructing it
- Stop overriding locked root account when launching emergency shell
- Redirect systemd generator's stdout to kmsg

Release 0.2.0

---

systemd/coreos-installer-service

More networking kargs we should probably persist. This came from
some user feedback about RHCOS missing this ability.

systemd: coreos-installer-service: persist net.ifnames net.naming-scheme kargs

---

dracut/30coreos-installer/parse-coreos.sh

dracut hooks are sourced which means if we exit 0 here then we'll
stop parsing the rest of the hooks (after 90).

fix coreos-installer dracut module

---

.cci.jenkinsfile

That's so 2 days ago!
https://github.com/coreos/coreos-assembler/pull/1418

ci: stop passing --osmet switch to buildextend-live

---

src/osmet/fiemap.rs

I switched to rust-analyzer (it's pretty awesome) and it warns
about the unused parens here.

osmet: Remove unused parenthesis

---

src/blockdev.rs
src/cmdline.rs
src/osmet/mod.rs

Pairs with: coreos/coreos-assembler#1483
We want RHCOS to support offline installs too (it's key to the UX)
but the LUKS container complicates things.  We discussed changing
the RHCOS LUKS bits to save the header in e.g. `/boot` but it's
a big change to that code, and introduces yet another layout
when we really want to switch to Ignition+LUKS.

pack: Support --real-rootdev for RHCOS+LUKS

---

Cargo.toml

Make life easier for packagers.
cc @lucab @jlebon

cargo: relax osmet dependencies

---

.cci.jenkinsfile

Manually enumerate subcommands, since there doesn't seem to be a great way to do it programmatically.

ci: check line lengths of help text

---

src/cmdline.rs
src/download.rs
src/install.rs
src/source.rs

This matches our support for it for the disk image.
A big difference though is that we don't usually have GPG signatures for
integrity checking and authenticity. At the very least, we refuse to
fetch over pure HTTP without passing `--ignition-hash` or
`--insecure-ignition`. (I didn't want to wrap this under the same
`--insecure` switch since one may still want to verify signatures on the
disk image itself).
Closes: #118

install: add --ignition-url

---

systemd/coreos-installer.service
systemd/coreos-installer.target

On Fedora 32, an `OnFailure` directive in a target unit [no longer does anything](https://github.com/systemd/systemd/issues/14142#issuecomment-634946368).
Reported by @nikita-dubrovskii.

systemd: move OnFailure into coreos-installer.service

---

src/cmdline.rs
src/install.rs

```
commit b7e7a01b6d308fe7b85751cefc1f31cd3793db17
Date:   Thu Jun 11 11:41:59 2020 -0400
install: factor out function to walk BLS configs
Prep for next patch.
commit 25c71d62f937d52970f85be2294b4f166983d908
Date:   Tue Jun 16 16:38:46 2020 -0400
install: rename --firstboot-args to --append-firstboot-kargs
Let's use a more precise name for this switch. First, specify that it
*appends* to the list of firstboot arguments. Second, use `kargs`
instead of just `args` to be more clear.
This is prep for new switches which will use the same naming convention.
commit 70371c47ab76b78f522e4469906e05e1edd05c6d
Date:   Tue Jun 16 17:15:41 2020 -0400
install: test platform ID restamping bits
Factor out the closure and add some basic unit tests.
```

Prep patches for modifying kargs

---

src/cmdline.rs
src/install.rs

This allows users to delete and append kernel arguments from the default
set. The major use cases for this are (1) avoiding an additional reboot
which might be costly in some situations, and (2) making it easier to
troubleshoot the system on firstboot.
For more details, see
https://github.com/coreos/fedora-coreos-tracker/issues/533#issuecomment-642234015.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/533

install: add --delete-karg and --append-karg

---

scripts/coreos-installer-service

We no longer need to run curl by hand.
cc @jlebon

systemd: use --ignition-url in service wrapper

---

src/download.rs

We were accidentally writing out the real data, and then going back afterward and writing it again.
Fixes #167.

 download: correctly zero first MiB of disk during initial write

---

src/download.rs
src/install.rs
src/io.rs
src/iso.rs
src/main.rs
src/osmet/file.rs
src/osmet/io_helpers.rs
src/osmet/mod.rs
src/osmet/unpacker.rs

The `std` one uses an 8 KiB buffer.  Use a larger buffer to amortize syscall overhead.

 *: use our own std::io::copy() implementation

---

Dockerfile
src/blockdev.rs
src/install.rs

Handle partitioning with `kpartx`, and rely on the `lsblk` + `holders` busy-partition check to ensure exclusivity.
Fixes #91.  Alternative to #211.

blockdev: support installing to DM devices

---

.travis.yml
Cargo.lock
Cargo.toml
scripts/coreos-installer-service
src/blockdev.rs
src/download.rs
src/install.rs
src/io.rs
src/main.rs
src/s390x/README.md
src/s390x/dasd.rs
src/s390x/mod.rs
src/s390x/zipl.rs

Installation on s390 dasd disks is a bit tricky,
this patch makes coreos-installer able to format,
create partitions, and finally install CoreOS on s390.

s390x: add support for IBM Z DASD disks 

---

Cargo.toml

The bump to major 4 just adds serde support, which we don't need.  Ease downstream packaging.

cargo: allow byte-unit major 3 or 4

---

Cargo.toml
Makefile
dracut/50rdcore/module-setup.sh
src/bin/rdcore/cmdline.rs
src/bin/rdcore/main.rs
src/lib.rs
src/main.rs

I thought I'd gauge interest in this approach before going too deep into it. My immediate goal here is to re-implement the logic for https://github.com/coreos/fedora-coreos-config/pull/503 into `rdcore`.
```
commit a1592f9a84dd8fa29d5c8be62e739a6af3f5b144
Date:   Mon Jul 20 17:35:20 2020 -0400
Move logic to `libcoreinst` library
Create a new `libcoreinst` library which contains all the logic, and
make `coreos-installer` simply consist of `main.rs` which calls into it.
This is prep for adding another binary which will reuse code in
`libcoreinst`. Doing it this way is a bit awkward, because e.g.
`cmdline` is also in the library, but it allows minimal churn while
still making it easy to add other binaries.
commit 14016f3bcd49dd84891211add0ed4b3d7e54da55
Date:   Mon Jul 20 17:35:21 2020 -0400 …
```

Split out a `libcoreinst` library and add a new `rdcore` binary

---

src/cmdline.rs
src/osmet/mod.rs

On my machine, with coreos-installer built in release mode, this reduces a cosa `osmet-pack` invocation from 71s to 42s (and there are two of them in a `buildextend-live`), while increasing osmet file size from 5 MiB to 7.4 MiB.
We could presumably do better by swapping out the compression algorithm in this case, but that would require a file format change and some additional code complexity.

osmet: add pack --fast option for worse compression

---

src/blockdev.rs
src/install.rs
src/osmet/mod.rs

The partition itself is a `crypto_LUKS` volume; we want the DM device attached to it.  Relax the holders filter in this case.
Fixes 87d2c72cc5c7.

osmet: successfully mount RHCOS root filesystem for packing

---

Cargo.lock
Cargo.toml
src/blockdev.rs
src/cmdline.rs
src/install.rs
src/io.rs

The API of `openssl::sha` is _not good_, but it's faster than `sha2` and we're already using it in osmet.

install: support Ignition sha256- hash type; switch from sha2 crate to OpenSSL

---

src/bin/rdcore/cmdline.rs
src/bin/rdcore/main.rs
src/bin/rdcore/stream_hash.rs

This command copies a stream from stdin to stdout, verifying the data via SHA-256 as it goes.  It receives an input file in the following format:
```
stream-hash sha256 <block-size>
<hexdigest>
<hexdigest>
<hexdigest>
...
```
The idea is that we can read `block-size` bytes into RAM, check their digest, send them to the next program in a shell pipeline, and move on to the next hash.  This lets us safely unpack a streaming download while verifying it, and is intended for downloading the PXE rootfs image.

rdcore: add stream-hash subcommand

---

Cargo.lock
Cargo.toml

Minor changes:
- install: Support `sha256` hashes in `--ignition-hash`
- rdcore: Add new program and Dracut module for internal use in the CoreOS initramfs
- rdcore: Add `stream-hash` subcommand for streaming verification of downloads
- osmet: Add `pack --fast` option for use in development builds
- osmet: Fix packing root filesystem wrapped in a `crypto_LUKS` container
- Allow `byte-unit` 3.x or 4.x
- Drop `sha2` dependency

Release 0.4.0

---

README.md

Many users won't need them.  Let's keep the argument list minimal.

README: drop console= kargs from PXE setup

---

src/download.rs
src/install.rs
src/io.rs
src/iso.rs
src/osmet/file.rs
src/osmet/mod.rs
src/osmet/unpacker.rs
src/s390x/dasd.rs

The current image pipeline is:
- local file or HTTP response →
- [some Readers that don't affect I/O size] →
- `BufReader` with 8 KiB buffer →
- decompressor →
- `copy()` with 256 KiB buffer →
- disk.
`copy()`'s large buffer doesn't matter here.  The decompressor will read data in whatever chunk size it wants, which will be aggregated only up to 8 KiB.  The decompressor will also produce data in whatever chunk size it wants, depending on the compressed stream, and those chunks won't be aggregated at all.
Upgrade the `BufReader` to a 256 KiB buffer and add 256 KiB `BufWriter`s.  This doesn't seem to affect performance much in my local tests, but it's still the right thing to do.  Switch back to `std::io::copy`, since our reimplementation was misguided; add buffers in notable places …

Drop copy() reimplementation; use buffered I/O with larger buffers

---

Cargo.lock
Cargo.toml
src/download.rs

Implement our own Reader and drop the `progress_streams` dependency.

download: refactor progress reporting

---

systemd/coreos-installer-disable-device-auto-activation.service

The service was racing with `tmp.mount` because bash here-documents will fail if `/tmp` isn't writable.

systemd: fix intermittent failure disabling device auto-activation

---

systemd/coreos-installer-noreboot.service
systemd/coreos-installer-reboot.service

The names of the services should be an implementation detail.  Currently, any user-injected post-install units need to sequence
After=coreos-installer.service
Before=coreos-installer-reboot.service
Before=coreos-installer-noreboot.service
This way, they can just sequence
After=coreos-installer.service
Before=coreos-installer.target

systemd: sequence reboot/noreboot services after primary target

---

src/blockdev.rs
src/install.rs
src/io.rs

resolve_symlink doesn't return an absolute path, so we can get as result smth like `../../devname`. For s390x
with DASD it breaks the installation, becase we use `/dev/dasd` as pattern in `is_dasd()`

io: use std::fs::canonicalize instead of resolve_symlink

---

.cci.jenkinsfile
src/bin/rdcore/cmdline.rs
src/bin/rdcore/main.rs
src/bin/rdcore/rootmap.rs
src/blockdev.rs
src/install.rs

The `rootmap` command will handle (1) discovering root block device
dependencies, (2) generating appropriate kernel arguments for each block
device, and (3) optionally injecting these kernel arguments into the BLS
config.
This is necessary in order to implement root on complex devices, such as
LUKS or RAID, as described in:
coreos/fedora-coreos-tracker#94

rdcore: add rootmap command

---

Cargo.lock
Cargo.toml
README.md
scripts/coreos-installer-service
src/blockdev.rs
src/cmdline.rs
src/download.rs
src/errors.rs
src/install.rs
src/io.rs

Add `--save-partlabel <glob>` and `--save-partindex <range>` options, which save partition table metadata for existing data partitions and then restore those partitions after writing the image.  `--save-partlabel` takes a glob pattern matching the partition label, and `--save-partindex` takes a partition number or range of partition numbers (possibly single-ended).  For example, to save all partitions with indexes greater than 4, specify `--save-partindex 5-`.  The specified partitions need not exist.  If no `--save-*` options are specified, no partitions are saved.
Multiples of each option can be specified, and/or multiple filters can be specified within a single option argument by separating them with commas.  There are corresponding kargs `coreos.inst.save_partlabel` and …

Add partition preservation

---

Cargo.lock
Cargo.toml

Major changes:
- install: Add `--save-partlabel` and `--save-partindex` options to preserve specified partitions
- systemd: Add `coreos.inst.save_partlabel` and `coreos.inst.save_partindex` kargs
Minor changes:
- install: Fix installing to DASD via symlink
- systemd: Fix intermittent failure disabling MD-RAID and DM device activation
- systemd: Sequence `reboot`/`noreboot` services after `coreos-installer.target`
- Increase I/O block size when copying data, correctly
- rdcore: Add `rootmap` subcommand to generate kargs for root device dependencies
- Don't build `rdcore` binary unless `rdcore` feature is enabled
- Add `glob` and `uuid` dependencies
- Drop `progress-streams` dependency
- Depend on `gptman` on all CPU architectures

Release 0.5.0

---

.travis.yml

```
commit 163d0a37e7ff1af97de36458a39172d6bfdeedec
Date:   Wed Aug 5 09:38:27 2020 -0400
ci/travis: bump MSRV to 1.44.1
This is in the el8 buildroot now.
commit df8224c979b66a4d954c0624db21709e5b56e924
Date:   Wed Aug 5 09:39:27 2020 -0400
ci/travis: use MSRV for clippy
It's not helpful to developers to have to keep around two separate
toolchain versions for hacking on this codebase. Let's just use the MSRV
for clippy too. It moves fast enough nowadays too.
commit 92de71b3befe8d71998066f35fdb84461ba66652
Date:   Wed Aug 5 09:42:52 2020 -0400
ci/travis: also run `rustfmt --check`
```

ci/travis: various changes

---

.cci.jenkinsfile
src/cmdline.rs
src/download.rs
src/errors.rs
src/io.rs
src/live.rs
src/main.rs

Add subcommands to generate or show a cpio.xz-wrapped Ignition config for appending to a PXE initrd.
Also switch `iso ignition embed` to using xz (and `iso ignition show` to accepting either gz or xz); it uses storage more efficiently and is supported by both FCOS and RHCOS.
Requires #343.  Fixes #322.

live: add pxe ignition {wrap|unwrap} subcommands

---

src/blockdev.rs

Otherwise we fail in the vanilla case of no rootfs changes.

blockdev: handle ENOENT when looking for device deps

---

src/blockdev.rs
src/download.rs
src/install.rs
src/io.rs
src/s390x/dasd.rs

Suppose, by way of example, that Ignition injection fails during an install with saved partitions.  The primary GPT has the following contents over time:
1.  zeroed while performing the download,
2.  image partitions after the download,
3.  image partitions plus saved partitions before mounting Ignition configs,
4.  zeroed after Ignition injection fails,
5.  saved partitions.
Thus, if we fail during a phase where the saved partitions are not on disk, it's important to recover from the failure and rewrite the GPT.  We have good unit tests on the low-level pieces, but the high-level error paths in `install.rs` will rot and there have already been bugs.  Also, there are circumstances we don't handle, such as power loss (of course) and Unix signals.
This happened because partition saving was …

Continuously maintain saved partitions in GPT

---

src/cmdline.rs

cmdline: fix incorrect deprecation warning for "iso ignition remove"

---

src/bin/rdcore/rootmap.rs
src/util.rs

Because we now always inject a `root` karg, it means that it's systemd
which does the mount. But then, systemd doesn't know to use the
`prjquota` flag we want by default for xfs.
Call out to a `coreos-rootflags` helper where the source of truth for
default root mount flags lives and embed its output if any is provided.

rdcore/rootmap: also inject rootflags karg

---

src/install.rs
src/s390x/zipl.rs

This is necessary for `coreos-installer-service` to capture live boot kargs such as static IP address configs.  `ignition-firstboot-complete.service` will rerun `zipl` during the first boot.
Fixes #364.

s390x: include firstboot kargs in zipl run

---

Cargo.lock
Cargo.toml

Major changes:
- Add `pxe ignition` subcommands to generate or show an Ignition config wrapped in an appendable initrd
- iso: Move `iso` subcommands to `iso ignition` and deprecate the former
- iso: Rename `iso ignition embed -c`/`--config` to `-i`/`--ignition-file`
Minor changes:
- install: Fix kernel ignoring saved partitions after install failure
- install: Fix loss of saved partitions if original partition table is invalid
- install: Retain saved partitions in partition table at all times during install
- install: Clear partition table on failure by writing empty GPT rather than zeroes, except on DASD
- install: Reread kernel partition table after restoring partitions on failure
- install: Make `--preserve-on-error` saved partition stash file the same size as the target disk
- …

Release 0.6.0

---

.cci.jenkinsfile

These are just containers for subcommands, but it doesn't hurt to be complete.

ci: add some more checklens for good measure

---

src/blockdev.rs

Miscompilation also affects other parts of the codebase, and the original code is cleaner.
This reverts #360.  See #372.
cc @nikita-dubrovskii @Prashanth684

Revert "blockdev: use loop instead of iterator"

---

src/bin/rdcore/rootmap.rs

If the root device has `_netdev` we need to add that to the kernel
cmdline so systemd knows to order the generated unit after networking.

rdcore/rootmap: add rd.luks.options=_netdev if needed

---

Cargo.lock
Cargo.toml
src/live.rs

On filesystems and kernels that support it, use `copy_file_range` to
copy the ISO file. CoW semantics is a good fit here because the
transformations we do on the output file are minimal anyway, so there
isn't really a question of balancing against delayed copy costs.
This brings down the time to inject an Ignition config from 4s to 50ms
on my computer.
To do this, use `openat-ext`'s `FileExt` trait which supports doing
`copy_file_range` on `File` objects. (`std::fs::copy()` also knows
`copy_file_range`, but it only takes file paths, so we'd lose the
`O_EXCL | O_CREAT` semantics we want here).

iso: use copy_file_range to copy the ISO if possible

---

.cci.jenkinsfile

For some marginal CI testing speed gains.

ci: compress metal4k image with `--fast`

---

src/blockdev.rs
src/download.rs

When installing with saved partitions, we were failing to clear the MBR boot code during install and on error, and failing to write the new boot code afterward.  Fixes regressions in #340.
Also update the size of the protective MBR partition after install, for consistency with the GPT.
https://bugzilla.redhat.com/show_bug.cgi?id=1879690

Properly update MBR when installing with saved partitions

---

Cargo.lock
Cargo.toml

Minor changes:
- iso: Use filesystem copy-on-write mechanism for `-o` output file if available
- install: Remember to update MBR from install image when restoring saved partitions
- install: Update size of protective MBR partition when restoring saved partitions
- install: Clear MBR boot code on install failure
- install: Revert insufficient s390x segfault avoidance change
- docs: Restructure for web publishing
- docs: Add initial command-line reference
- rootmap: Configure LUKS root to wait on network if needed
- Require `openat-ext` &ge; 0.1.4
SHA-256 digests:
- crate: ``
- vendor: ``

Release 0.7.0

---

systemd/coreos-installer.service

If the system is configured to use systemd-resolved (i.e.
systemd-resolved is enabled) then start coreos-installer after
systemd-resolved. Otherwise we get race conditions where
coreos-installer starts before resolved is up and we get errors like:
```
Starting Network Name Resolution...
[  OK  ] Finished Network Manager Wait Online.
[  OK  ] Reached target Network is Online.
Starting CoreOS Installer...
[   12.949935] coreos-installer-service[889]: coreos-installer install /dev/sda --ignition-url https://dustymabe.fedorapeople.org/user-systemd.ign --insecure-ignition
[   13.007728] coreos-installer-service[907]: Error: parsing arguments
[   13.008549] coreos-installer-service[907]: Caused by: downloading source Ignition config https://dustymabe.fedorapeople.org/user-systemd.ign
[ …
```

systemd: start coreos-installer service after systemd-resolved

---

systemd/coreos-installer.service

Follow up to 139c2db. Add a comment to the open issue for retrying
HTTP requests in coreos-installer.

systemd: add context to systemd-resolved unit order

---

Cargo.lock
Cargo.toml

~~Changes:~~
~~- signing-keys: drop F31, add F33/F34 signing keys~~
~~- systemd: start coreos-installer service after systemd-resolved~~
~~- systemd: add context to systemd-resolved unit order~~
~~- Dockerfile: update to F33~~
Major changes:
- Add Fedora 33 and 34 signing keys; drop Fedora 30 signing key
Minor changes:
- systemd: Start coreos-installer service after systemd-resolved
- Update container to Fedora 33
SHA-256 digests:  
- crate: ``
- vendor: ``

Release 0.7.1

---

Cargo.lock
Cargo.toml

Major changes:
- Add Fedora 33 and 34 signing keys; drop Fedora 30 signing key
Minor changes:
- systemd: Start coreos-installer service after systemd-resolved
- Update container to Fedora 33
SHA-256 digests:  
- crate: ``
- vendor: ``

Release 0.7.2

---

.github/ISSUE_TEMPLATE/release-checklist.md

This will update the release instructions to clarify the step while publishing a release and the `UPSTREAM_REMOTE` keyword.

github: update the release instructions

---

src/blockdev.rs

These were all triggering `clippy::unnecessary_lazy_evaluations`:
https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations

blockdev: fix clippy complaints

---

src/blockdev.rs
src/cmdline.rs
src/install.rs
src/s390x/dasd.rs

This a  fix for:
https://bugzilla.redhat.com/show_bug.cgi?id=1905159
Unformatted (low-level) ECKD DASD's sector size is 512 bytes by default:
```
$ fdasd -p /dev/dasdb
fdasd error:  Unsupported disk format
$ ioctl_sector_size
/dev/dasdb: 512
```
So `coreos-installer` chooses 512 bytes-sector `osmet` image.
After formatting (`dasdfmt`) we end up with 4096 bytes sector size, and therefore `coreos-installer` cannot install previously selected `osmet` image

s390x: use recommended blocksize of 4096 bytes for unformatted ECKD DASD disks

---

src/bin/rdcore/cmdline.rs
src/bin/rdcore/kargs.rs
src/bin/rdcore/main.rs
src/bin/rdcore/rootmap.rs
src/cmdline.rs
src/install.rs

We already have the code for modifying kargs in BLS configs. This
command just exposes it.
It's useful generally, but the motivation right now is for the root
filesystem migration script in RHCOS 4.7 which will use this once moved
to the initramfs for openshift/os#448.

rdcore: add `kargs` subcommand

---

Cargo.lock
Cargo.toml
src/cmdline.rs
src/s390x/dasd.rs
src/s390x/eckd.rs
src/s390x/fba.rs
src/s390x/mod.rs

There are 2 types of DASD devices:
- ECKD (Extended Count Key Data) - is regular DASD of type 3390
- FBA (Fixed Block Access) - is used for emulated device that represents a real SCSI device
Only ECKD-DASD disks require `dasdfmt, fdasd` linux tools to be configured.

s390x: add FBA-DASD disks support

---

Cargo.lock
Cargo.toml

Major changes:
- Add `iso kargs` subcommand for modifying kernel arguments in live ISO images
- Support IBM Z FBA DASD target devices
Minor changes:
- Fix race condition causing `fdasd` failure when formatting ECKD DASD
- Fix sector size selection on unformatted ECKD DASD
- rdcore: Add `kargs` subcommand for modifying BLS configurations
- Add `lazy_static` dependency
- Add `mbrman` and `rand` dependencies on s390x
- Require `regex` &ge; 1.4

Release 0.8.0

---

src/blockdev.rs

`lsblk` by default outputs the target device followed by all its reverse
dependencies. But interestingly, when using `--pairs`, the `lsblk` in
RHCOS seems to output the reverse dependency first before the target
device.
We were relying on correct ordering in `lsblk_single`, where all we care
about is the target device. Instead, explicitly use `--nodeps` in that
case so that `lsblk` knows to only print the target device. (The
`lsblk()` helper actually used to support that, but it was removed in
88de4fc.)
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1916502

blockdev: use --nodeps when querying single device

---

src/cmdline.rs
src/osmet/mod.rs

This is no longer required now that RHCOS has moved to
LUKS-via-Ignition, so we can simplify things.
Goes together with https://github.com/coreos/coreos-assembler/pull/2025.

osmet: drop support for --real-rootdev

---

src/live.rs

Explicitly separate the in-place and copied behaviors.  Use `NamedTempFile` for the copied case, rather than writing directly to the final location and deleting the output file on failure.  Add explicit support for streaming the output to stdout.
This will set the copied output file mode to `0600`, which seems okay because the embedded Ignition config may contain secrets.  It also ensures that the permanent filename is not used until the file is completely written.
cc @djzager @jlebon
Requires #432.

iso: refactor CopiedFileHolder as an enum and rename to ContentFile

---

src/s390x/eckd.rs

During migration from `error-chain` to `anyhow` s390x-code wasn't fully updated. Fix this

s390x: fix build

---

.github/workflows/rust.yml
src/bin/rdcore/cmdline.rs
src/cmdline.rs
src/download.rs
src/osmet/unpacker.rs

https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_wraps

*: fix clippy::unnecessary_wraps lint on 1.50; use newer clippy in CI

---

src/blockdev.rs

Apart from the `/dev/mapper` symlinks, there's a bunch of other possible
symlinks which also point to the same devmapper device. Instead of
trying to catch them all, simply resolve all symlinks and then check
that it starts with `dm-`.
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1886229#c39

blockdev: strengthen device mapper path detection

---

src/bin/rdcore/cmdline.rs
src/bin/rdcore/kargs.rs

For testing the semantics of `rdcore kargs`, it's helpful to just be
able to directly pass the `options` string we want it to modify. Let's
add a switch to make that easier.
Best viewed with whitespace ignored.

rdcore/kargs: add hidden --override-options switch

---

.cci.jenkinsfile
.github/workflows/rust.yml
tests/help.sh

Add a shell script so developers can run the check by hand.  Move the CI test into GitHub Actions to make it more accessible to downstream forks.

ci: move help text line length test to GitHub Actions

---

src/blockdev.rs
src/install.rs
src/osmet/mod.rs

Proposed solution for #512
Sometimes disks may be given by a path that looks something
like `/dev/disk/by-id/wwn-0x5555555555555555`. This path is
a symlink to the actual `/dev/*` device.
This commit prevents a confusing error message from showing
when the installer is given a busy disk that is a symlink to
a `/dev/*` device and not an actual `/dev/*` directly.
The solution used here is simply resolving the symlink before
creating a `Disk` object. This is done because code later down
the line assumes that the path is going to have a `/dev/*` format.

Resolve symlink disk paths when creating `Disk` objects

---

Dockerfile

Fedora 34 includes glibc 2.33, which tries to opportunistically implement `faccessat()` using `faccessat2()`, which is blocked on quay.io builders by a seccomp policy, which returns `-EPERM` instead of `-ENOSYS`, which glibc treats as a fatal error.
https://issues.redhat.com/browse/PROJQUAY-2006
This reverts commit 64d0ee4208ec01b14a6022b0aab1d3b978d08b27.

Revert container to F33 to fix quay.io build failures

---

src/bin/rdcore/rootmap.rs

Teach the rootmap to ignore multipath devices since they don't need any
special handling.
Normally, in multipath mode, one doesn't hit the rootmap code because
users have to specify `root=`, which skips rootmap injection. But we do
encounter it in the LUKS-on-multipath case where we still want rootmap
to inject e.g. `root=/dev/mapper/myluksdev`.
(In the future, one could imagine multipath being Ignition-driven rather
than something getting enabled behind Ignition's back. Then, rootmap
here would indeed add e.g. `rd.multipath=1` to the kargs cmdline. For
now, this is all done "out-of-band".)

rdcore/rootmap: ignore multipath devices

---

Cargo.lock
Cargo.toml

Major changes:
- Add Fedora 35 signing key; drop Fedora 32 signing key
Minor changes:
- install: Fix block device path in error message when disk is busy
- install: Ignore corrupt GPT on target disk unless saving partitions
- rootmap: Ignore multipath devices
Edited

Release 0.9.1

---

src/cmdline.rs

The top-level `coreos-installer` command prints a list of subcommands if run without arguments, but subcommands with subcommands don't:
$ target/debug/coreos-installer iso
Error: parsing arguments
Caused by:
unrecognized 'iso' subcommand
Enable the automatic subcommand list for subcommands with subcommands.  Don't enable it globally because that would enable it for leaf commands, which precludes zero-argument commands like `list-stream`.

cmdline: don't require `-h` to list subcommands

---

src/blockdev.rs

This ensures that other processes on the system can't get file descriptors to files in our mounts, which would impede unmount.  It also guarantees that our mounts are unmounted even if we crash hard (though `kpartx` wouldn't be undone, if applicable).
In contrast to the discussion in #208, we hard-fail if unshare fails.  `CAP_SYS_ADMIN` is required for both `mount()` and `unshare(CLONE_NEWNS)`, and we recommend running containers privileged, so there shouldn't be any expected unshare failures.  This avoids accidentally depending on private namespace semantics while not necessarily getting them.
Fixes #208.
cc @jlebon @dustymabe @nikita-dubrovskii

blockdev: mount filesystems into private namespace

---

src/blockdev.rs

When we use DeviceMapper disk as `coreos.inst.install_dev=`, it may happen that `kpartx` fails to reread
partition table, and therefore fails the installation. Let's try up to 5 times, before giving up
```
[   16.056589] coreos-installer-service[1333]: device-mapper: resume ioctl on mpatha4  failed: Invalid argument
[   16.057027] coreos-installer-service[1333]: resume failed on mpatha4
[   16.057050] coreos-installer-service[1333]: Error: "kpartx" "-u" "-n" "/dev/dm-0" failed with exit code: 1
[   16.057069] coreos-installer-service[1333]: Retrying in 1 second
[   18.362478] coreos-installer-service[1333]: Read disk 20.3 MiB/3.5 GiB (0%)
[   23.399255] coreos-installer-service[1333]: Read disk 116.7 MiB/3.5 GiB (3%)
[  216.402889] coreos-installer-service[1333]: Read disk 3.5 GiB/3.5 GiB …
```

blockdev: try rereading partition table up to 5 times

---

src/install.rs

The Ignition config may contain secrets.  Don't expose it, or anything in its parent directory, to unprivileged processes.

install: restrict access permissions on /boot/ignition{,/config.ign}

---

Cargo.toml

On my system, running a dev build, this reduces install time of an image compressed with `gzip -1` from 6m45s to 9.5s.
This should fix CoreOS CI timeouts on the metal4k image.
I don't think this is related to #184, but linking it here for completeness.

cargo: optimize gunzip inner loops in dev builds

---

Cargo.toml
src/bin/rdcore/kargs.rs
src/bin/rdcore/stream_hash.rs

Other services in the initrd may want to use the same flag file to coordinate reboots.  See discussion in https://github.com/openshift/os/pull/574#discussion_r675688876.
Requires https://github.com/coreos/coreos-installer/pull/579 to fix CI.

rdcore/kargs: don't fail if --create-if-changed file already exists

---

docs/getting-started.md

RHCOS versions that shipped it are no longer supported.

docs/getting-started: drop reference to legacy branch

---

docs/cmd/download.md
docs/cmd/install.md
scripts/coreos-installer-service
src/cmdline.rs
src/download.rs
src/source.rs

We're hitting issues in RHCOS right now where it's possible that
`coreos-installer.service` is racing with networking being fully up,
even though we're ordered after `network-online.target` and
`systemd-resolved.service` (though RHCOS doesn't use the latter).
The issue may not be a race in the end, but misconfigured networking.
But anyway, we really should be retrying fetches.
I gated this behind a switch instead of doing it by default for all
fetches, because e.g. interactively I think it makes more sense not to
retry. (And similarly for other commands like `download` and
`list-stream`).
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1974411
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1967483
Closes: #283

Add `coreos-installer install --fetch-retries`

---

src/install.rs
src/s390x/zipl.rs

On s390x this simplifies installation of `zipl`. 
Also could be used for https://github.com/coreos/coreos-installer/pull/533

s390x: simplify zipl installation

---

.github/workflows/containers.yml
.github/workflows/rust.yml

workflows: bump toolchains; restrict repository access

---

Cargo.lock
Cargo.toml

Major changes:
- install: Support IBM Z virtio DASD target devices
- install, download: Support retrying fetches with new `--fetch-retries` option
Minor changes:
- install: Restrict access permissions on `/boot/ignition`
- install: Retry reading partition table on device mapper target devices
- systemd: Persist `coreos.force_persist_ip` kernel argument when installing with `coreos.inst.*`
- List subcommands of a command even without `-h`
- Mount filesystems in a separate mount namespace
- Refactor bootloader installation on s390x
- Enable optimization for gzip code in dev builds to speed up testing
- docs: Document `coreos-installer iso kargs` commands
- kargs: Run `zipl` if necessary on s390x
- kargs: Don't fail `--create-if-changed` if the file already exists
Packaging …

Release 0.10.0

---

src/bin/rdcore/cmdline.rs
src/cmdline.rs

Make some configuration changes to match the outcome of the `structopt` PR (https://github.com/coreos/coreos-installer/pull/594).

Prep patches for `structopt` conversion

---

docs/getting-started.md

docs: Use security-opt label=disable for ISO & PXE download
Only disable SELinux labelling for ISO & PXE download as we only need
access to the current directory and not all privileges granted by
`--privileged`.
---
docs: Split long lines to improve readability

docs: Use security-opt label=disable for ISO download

---

src/bin/rdcore/cmdline.rs
src/bin/rdcore/kargs.rs

In the live ISO/PXE case, Ignition kargs stage has nowhere to write the new kargs, but should still succeed if no changes need to be made.  Add `--current` to apply the kargs changes to the contents of `/proc/cmdline`.  The Ignition kargs wrapper can use this with `--create-if-changed` to decide whether to fail.

rdcore/kargs: add `--current` to do a dry run on current kargs

---

dracut/50rdcore/module-setup.sh

When zipl deals with device-mapper targets, it potentially requires an
additional helper script. Install this in the initramfs.
This fixes https://github.com/openshift/os/issues/615.

dracut: also ship zipl_helper.device-mapper on s390x

---

.cci.jenkinsfile

Now that we have rdcore, changes to this repo affect more than the install path.  Do a full kola run.
Also switch to the coreos-ci-lib function for `kola testiso`.

ci: run kola tests; use coreos-ci-lib helper for kola testiso

---

src/cmdline.rs
src/install.rs

The call to dasd_try_get_sector_size() was shuffled around, adjust the
use paths accordingly.
Fixes: ae1f4a79bfcc ("cmdline: move all postprocessing into command implementations")
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>

install: fix call to dasd_try_get_sector_size() on s390x

---

src/osmet/mod.rs

You never know when you might want a machine-readable extent map.

osmet: produce JSON from `fiemap` debug subcommand

---

Dockerfile

coreos-installer now successfully builds in Quay on Fedora 34.

Dockerfile: update to F34

---

src/bin/rdcore/stream_hash.rs
src/live.rs
src/osmet/mod.rs

The repeated lock/unlock overhead shouldn't matter for trivial amounts of I/O, but it's good to establish a consistent pattern.
For https://github.com/coreos/coreos-installer/pull/616#discussion_r705320940.

*: lock stdin/stdout before doing I/O

---

.cci.jenkinsfile
src/cmdline.rs
src/iso9660.rs
src/lib.rs
src/live.rs
src/main.rs
tests/help.sh
tests/iso-inspect.sh

We do a lot of sophisticated things with our live ISOs. An upcoming
patch will push things yet further by supporting embedding in the ISO a
compressed minimal version of itself.
Currently, these modifications (together with Ignition embedding and
kernel arg modifications) require support from coreos-assembler writing
pointers in the System Area section to other places in the disc. With
the minimal ISO work, we'll need to able to find every file on the disc,
which would grow the complexity of these hacks further.
This patch adds a basic parser for the ISO9660 filesystem. It only
understands the minimal set of things we need, but it should provide a
good base for cleaning up our current approach, as well as for adding
minimal ISO support in a future patch.
As a way to exercise the code, add …

iso: add minimal ISO9660 parser

---

.cci.jenkinsfile
src/cmdline.rs
src/iso9660.rs
src/lib.rs
src/live.rs
src/main.rs
tests/help.sh
tests/iso-extract-pxe.sh
tests/iso-inspect.sh

This commands allows users to easily extract the PXE artifacts from
CoreOS live ISOs without having to mount them, which may require
additional privileges.
There are other CLI tools which can do this of course, but having it
integrated makes it much easier and it's trivial to support with the new
ISO9660 parser.
It also establishes the `extract` subcommand, to which we'll add a
`miniso` command for the minimal ISO work.

iso: add `coreos-installer iso extract pxe`

---

Cargo.lock
Cargo.toml
src/download.rs
src/io.rs
src/iso9660.rs
src/live.rs

1. Remove from `LimitReader` the ability to return `Ok(0)` when the limit is reached.  Use `Read.take()` instead.
1. Drop the `IsoFs` `get_{dir,file}` wrappers in favor of new `try_into_{dir,file}` methods on `DirectoryRecord`.
1. Add `IsoFs.try_get_path()` method returning `Result<Option<DirectoryRecord>>`, for callers that can handle a missing path.

Some ISO 9660 refactoring

---

Cargo.toml

Similar to https://github.com/coreos/afterburn/pull/625

cargo: enable debuginfo in the release profile

---

src/cmdline.rs

Avoid having to write out `coreos-installer download --architecture` when downloading e.g. ISO or PXE artifacts for a different arch.  `coreos-installer install -a` is probably less common (though useful for e.g. writing SD card media) but add it too for consistency.

cmdline: add `-a` short option for `--architecture`

---

Cargo.toml
Dockerfile

If `lzma-sys` can't find development headers for `liblzma`, it builds its own copy.  Add `xz-devel` to the builder container so the containerized version uses Fedora's `liblzma` instead.  For the case where the developer doesn't have `liblzma` headers installed, avoid a 2x slowdown by building `lzma-sys` with optimization in the `dev` profile.
It appears that the Fedora package currently uses the system `liblzma` (by happenstance?) and the RHEL package currently bundles.  We'll want to add `BuildRequires: xz-devel` to both in any case.

Adjust for `lzma-sys` bundling `liblzma` if it doesn't find it

---

src/io.rs
src/iso9660.rs
src/live.rs
src/osmet/file.rs

Split out of https://github.com/coreos/coreos-installer/pull/559. See individual commit messages.

More prep patches for miniso work

---

src/download.rs

Some formats use compression as part of the format definition, without intending that the file should be decompressed before use.  For example, on non-x86 arches, the format sniffer detects the initramfs as a gzipped archive, but it's actually the concatenation of several cpio archives which might be compressed with different compressors.  Similarly, the aarch64 kernel is a regular gzip archive.
When `--decompress` is specified, only decompress files whose URLs have a `.gz`/`.xz` extension.  For consistency, always skip writing the signature in this case.
As a special case, do not decompress `.tar.gz` or `.tar.xz` files.  This is mostly to avoid decompressing the GCP `.tar.gz` image, which is meant to be uploaded to GCP as a unit.
If downloading from a mirror which has removed the …

download: only decompress if artifacts have `.gz`/`.xz` extension

---

src/blockdev.rs
src/install.rs
src/osmet/mod.rs

This is almost an exact revert of #308, which was necessary at the time
when RHCOS shipped with its rootfs inside a LUKS container. It no longer
does that, so let's simplify the code.

blockdev: drop support for querying partition holders

---

Cargo.toml

cargo: explicitly set `sign-tag`

---

.cci.jenkinsfile
src/cmdline.rs
src/lib.rs
src/live.rs
src/main.rs
src/miniso.rs

This command allows packing into the live ISO a minimal version of
itself which does not contain the root squashfs. The use case for
minimal ISOs has come up multiple times, notably in:
coreos/fedora-coreos-tracker#661
This is a sort of intermediate approach where we don't officially ship a
new artifact, but allow users to derive the minimal ISO from the
official live ISO.
The way this works is similar to osmet. It requires a "packing" step at
build time which adds an osmet-like file (the miniso data file) on the
full ISO itself. The data file describes how to construct a minimal ISO
from the full ISO. It weighs in at a few kilobytes, so the impact of the
size of the live ISO is negligible. If we ever officially do ship a
minimal ISO, it also allows for the possibility of matching its …

Add support for minimal ISO packing/unpacking

---

src/bin/rdcore/cmdline.rs
src/bin/rdcore/main.rs
src/bin/rdcore/rootmap.rs
src/blockdev.rs
src/install.rs

This command does a few things:
- adds a `boot=UUID=<uuid>` karg to ensure the rootfs mounts by UUID
- "claims" the bootfs for the rootfs by adding a stamp file and erroring
out if one already exists
- adds a GRUB dropin containing the boot UUID
A natural follow-up to this would be have `coreos-installer install`
optimistically pre-randomize the bootfs UUID and adding the stamp file,
though it's worth discussing separately.
Part of coreos/fedora-coreos-tracker#976.

rdcore: add `bind-boot` command

---

Cargo.lock
Cargo.toml

Major changes:
- Drop Fedora 33 signing key
- iso: Add `extract pxe` subcommand to extract PXE artifacts from ISO
- iso: Add `extract minimal-iso` subcommand to extract netboot ISO image from ISO
Minor changes:
- download: Ignore `--decompress` for artifacts that are meant to be used compressed
- download: Report the selected artifacts before starting download
- download/install: Avoid printing GPG verification result when we're ignoring it
- install: Report automatically selected OS, architecture, platform when downloading install image
- install: Report if multiple filesystems are labeled `boot`
- iso: Find Ignition embed area by directly parsing ISO filesystem
- iso: Find kargs embed areas by directly reading `kargs.json` from ISO, if available
- Add `-a` short option for …

Release 0.11.0

---

.cci.jenkinsfile

ci: stop providing no longer supported `--miniso` switch

---

src/iso9660.rs
src/miniso.rs

On ppc64le, some files are hardlinked. The way hardlinks are represented
in ISO9660 is simply that the dirents point to the same sector and have
identical sizes. So they show up as exact copies in the table. So we can
get rid of them by deduplicating. Rust's `Vec::dedup()` makes this easy.
See: https://github.com/coreos/coreos-assembler/issues/2583

miniso: handle hardlinked files

---

src/bin/rdcore/rootmap.rs

Devices that report type `linear` are md devices, even though the type doesn't start with `raid`.

rdcore/rootmap: properly handle linear md devices

---

src/bin/rdcore/rootmap.rs
src/blockdev.rs

Right now, to find the ESP devices, we just query all the devices on the
system with the matching partition type. This is clumsy though. E.g. in
case multipathing is in use, this will match both the multipathed
version and the non-multipathed versions.
Another case is multiple re-installs of the OS on different disks: we're
working to ensure that users don't have multiple boot filesystems, but
haven't so far required them to also wipe old ESPs. So we want to ensure
we only modify the ESPs on *our* boot disk.
Rework things by trying to be smarter: since we know what the right boot
filesystem is (`coreos-boot-edit.service` uses `--boot-mount`), use that
knowledge to derive the ESPs by only looking for them in the same
storage hierarchy.

bind-boot: look for ESPs on the same disk(s) as bootfs

---

src/blockdev.rs

This is a copy/paste from other instances of this. It's relevant as long
as we consider el7 a supported install platform (see
https://github.com/coreos/coreos-installer/issues/650). The particular
functions here aren't used yet at install time, but could in the future.
Anyway, we should probably instead have an `lsblk` command builder
helper where this lives just once.

blockdev: add comments about using `lsblk --paths` for el7

---

Cargo.lock
Cargo.toml
docs/cmd/install.md
scripts/coreos-installer-service
src/cmdline.rs
src/install.rs
src/io/hash.rs
systemd/coreos-installer-generator
systemd/coreos-installer.service

Add a repeatable `--config-file` option which specifies a YAML config file.  This contains command-line arguments that are prepended to the actual `coreos-installer install` command line before execution.  This will allow users to configure the install process without resorting to kernel arguments or replacing the `coreos-installer.service` unit.
Make the target device argument optional if a config file is provided, since the config file might specify it instead, but also do a late check in case the config file doesn't provide one either.
Implement config merging by generating a vector of synthesized command-line arguments, prepending it to the actual command line, and having structopt reparse the whole thing.  That allows structopt to apply any validation and constraints specified in …

install: support config files

---

scripts/coreos-installer-service

`coreos.inst=yes` no longer has any effect.  The `coreos.inst.install_dev=sda` syntax is still supported, and there are no plans to stop supporting it, but the new syntax is more consistent.  While our documentation tries to steer users toward the latter, examples of the old syntax keep showing up.  Add deprecation warnings to encourage users to update their configs.

scripts: print deprecation warnings for `coreos.inst=yes`, `coreos.inst.install_dev` without `/dev`

---

src/blockdev.rs
src/install.rs
src/live.rs
src/miniso.rs
src/osmet/file.rs
src/osmet/io_helpers.rs
src/s390x/eckd.rs
src/source.rs

It appears that anyhow has always supported `context()` and `with_context()` on `Option`, and we missed it during the error_chain conversion.

*: replace `ok_or_else` with `context`

---

.cci.jenkinsfile
docs/cmd/iso.md
docs/cmd/pxe.md
src/cmdline.rs
src/io/initrd.rs
src/live.rs
src/main.rs
tests/iso-ignition.sh
tests/iso-network.sh

An Ignition config for the live system might want to fetch remote resources, and the system might need non-default network configuration to do so.  This is possible in a limited way with kargs, but it's better to expose the full flexibility of NetworkManager keyfiles.
Add `iso` subcommands to `embed`/`extract`/`remove` network settings, and `pxe` subcommands to `wrap`/`unwrap` them.  These are analogous to the Ignition embed mechanism, and in the case of ISO images they share the same initrd and embed area.  NetworkManager keyfiles are deposited into `/etc/coreos-firstboot-network` in the initrd, which is supported by the OS
as of https://github.com/coreos/fedora-coreos-config/pull/1371.
The show/unwrap subcommands are a bit different than the Ignition ones, since there might be multiple …

live: add `iso`/`pxe` subcommands for embedding/wrapping NM keyfiles

---

Cargo.lock
Cargo.toml

Major changes:
- Add high-level [`iso customize`](https://coreos.github.io/coreos-installer/cmd/iso/#coreos-installer-iso-customize) and [`pxe customize`](https://coreos.github.io/coreos-installer/cmd/pxe/#coreos-installer-pxe-customize) subcommands for flexibly customizing a live image
- install: Add `--config-file` to specify install options via a YAML [config file](https://coreos.github.io/coreos-installer/customizing-install/#config-file-format)
- systemd: Automatically install if config files exist in `/etc/coreos/installer.d`
- Add [`iso network`](https://coreos.github.io/coreos-installer/cmd/iso/#coreos-installer-iso-network-embed) and [`pxe network`](https://coreos.github.io/coreos-installer/cmd/pxe/#coreos-installer-pxe-network-wrap) subcommands to embed NetworkManager configs in …

cargo: coreos-installer release 0.12.0

---

Cargo.toml
Dockerfile

LTO saves us 1.5 MB (11%) in the release binary with debug symbols disabled.  On the other hand it's been an enormous pain.  The RHCOS package disables LTO because of problems on s390x.  Quay and the Fedora armv7hl builders apparently OOM building 0.12.0 with LTO.  And it's not a default option in the first place.  Get rid of it.
Meanwhile, our binary size in the container is now 125 MB.  Disable debug symbols there to bring it down to 13 MB.  Symbols can make it easier to debug problems in production, but our bug reports don't generally take advantage of that, and the space requirement is excessive.

Disable LTO; disable debug symbols in container build

---

tests/images.sh

even when the caller supplies a build directory.  It takes 8 seconds on my system and avoids giving an incorrect impression that all tests have been run.
Followup to https://github.com/coreos/coreos-installer/pull/722#discussion_r771502341.

tests/images: always run tests against test fixtures

---

src/cmdline.rs
src/live/mod.rs
src/main.rs
src/osmet/mod.rs
tests/help.sh
tests/images.sh
tests/images/dev-show-iso.sh
tests/images/iso-ignition.sh
tests/images/iso-kargs.sh
tests/images/iso-network.sh

We've gradually accumulated hidden commands and options throughout the subcommand tree.  Some of these are deprecated, which is legitimate, but the rest are build-time/debug commands/options which developers might want to know about.  Since they're individually hidden, there's no discoverability other than by reading the source code.  And in the case of the debug options, the implementation is commingled with user-facing code.
Add a new `pack` command hierarchy for osmet and miniso packing (which form a private API with cosa) and a `dev` hierarchy for development commands (which have no stability at all).  Move everything relevant into them.  For the `pack` commands, leave the original commands as aliases until cosa can be updated.

Consolidate build/debug commands/options into separate command hierarchies

---

.github/workflows/env-setup
.github/workflows/rust.yml
src/s390x/fba.rs
src/s390x/zipl.rs

Run s390x tests in a Fedora container via a Fedora `qemu-user` static binary (since that one works, unlike the one in `ubuntu-latest`).  We can't use `actions-rs/toolchain` with an s390x container, so download and run `rustup` manually as well.  For consistency, use a Fedora container and manual `rustup` in the x86_64 tests too.
This gets us the s390x build, unit test, and lint coverage that we've been missing since switching away from Travis.

workflows: run tests in Fedora container; add s390x tests via qemu-user

---

.github/workflows/rust.yml

bitvec 0.22 requires it.  For some reason, s390x CI caught this but x86_64 didn't.  OCP 4.10 uses 1.52 and Fedora 35 uses 1.57, so this shouldn't break anything.

workflows: bump MSRV to 1.51

---

Cargo.lock

Fixes CVE-2021-32714 and CVE-2021-32715.

build(deps): bump hyper from 0.14.9 to 0.14.16

---

src/bin/rdcore/cmdline.rs
src/bin/rdcore/unique_fs.rs
src/blockdev.rs
src/install.rs

Partition table rereading is not always needed,
so it's beeter to let user decide if such behaviour
is required, i.e. after some changes were made to
filesystems, like change of UUID.

add flag for rereading partition table

---

.cci.jenkinsfile

ext.config.kdump.crash was failing the upstream CI for afterburn and coreos-installer repos so skipping them for these repositories.
Ref :coreos/fedora-coreos-config#1420 (comment)

ci: skip broken kdump.crash kola test

---

.github/ISSUE_TEMPLATE/release-checklist.md

templates/release-checklist: add packaging steps

---

Cargo.lock
Cargo.toml

Major changes:
- Add Fedora 37 signing key; drop Fedora 34 signing key
Minor changes:
- install: Drop support for `COREOS_INSTALLER_NO_MOUNT_NAMESPACE`
- install: Eliminate partition table reread delay on busy block devices
- Fix packing minimal ISO with empty files
- Move build-time packing commands to new `pack` subcommand
- Move developer-related commands to new `dev` subcommand
- Add `dev show initrd` and `dev extract initrd` subcommands
- verify-unique-fs-label: Add `--rereadpt` to reread partition tables first
- Disable LTO
- Disable debug symbols in container
- Require Rust ≥ 1.51.0

cargo: coreos-installer release 0.13.0

---

docs/customizing-install.md

Deemphasize customizing via kernel arguments and manual Ignition embedding, since `iso/pxe customize` has better UX.
Drop documentation of manual pre/post hooks, since it's very clunky and `iso/pxe customize` can handle this.

docs/customizing-install: update for `iso/pxe customize`

---

.copr/Makefile
.github/workflows/rpm.yml

```
commit d768073f4531ee3666a5206235d49fa83609c3f0
Date:   Tue Feb 15 12:23:37 2022 -0500
Add COPR integration Makefile
I'd like to enable auto-builds of this repo to
https://copr.fedorainfracloud.org/coprs/g/CoreOS/continuous/ so it could
eventually feed into
https://github.com/coreos/fedora-coreos-tracker/issues/910.
```
```
commit b9e7ec2b3bbe79b9dcc79d70c69b5459b92d8957
Date:   Tue Feb 15 12:31:03 2022 -0500
workflows: make TOOLCHAIN optional
For a future test, I'd like to ensure that we're using the Rust tooling
from Fedora. So let's make the rustup setup optional so we don't have to
worry about which `rustc` is actually being used.
```
```
commit 6ef95ab3a648a225a0f3874e69d611feb6ce47ec
Date:   Tue Feb 15 12:37:30 2022 -0500
workflows: add "RPM build" test
Verify that we can build …
```

Add COPR integration Makefile and add CI test for RPM building 

---

.github/workflows/rpm.yml

```
commit ed6b2a260bc109bec1ae5823cdbfec8f68646560
Date:   Tue Feb 22 09:51:14 2022 -0500
workflows/rpm: do full git clone
Notably, we want the tags so that the `git describe`-derived version is
valid. For CI test purposes, this doesn't really matter, but it makes
the artifacts archived more useful.
```
```
commit 64c5c9fb12011c9878e696163c8bdf582d808941
Date:   Tue Feb 22 09:53:36 2022 -0500
workflows/rpm: reword workflow and job name
It's verbose to have them both be "RPM build". Make the workflow "RPMs"
and the specific job "Build (Fedora)". This makes it more consistent
with the "Containers" workflow.
```

workflows/rpm: do full git clone and reword workflow and job name

---

src/blockdev.rs

This can help figuring out what went wrong.
Related: https://github.com/coreos/fedora-coreos-tracker/issues/1116

blockdev: print vendor dirs found

---

src/cmdline.rs
src/main.rs

coreos-assembler has been updated to use the new subcommands.
Requires https://github.com/coreos/coreos-assembler/pull/2631.

cmdline: drop legacy aliases for pack commands

---

.github/workflows/rust.yml
src/download.rs
src/live/mod.rs

Clippy has some false positives on the `to_string()` calls, which are necessary to prevent mixed mutable/immutable borrows.

Bump clippy to 1.59

---

.github/workflows/containers.yml
Dockerfile

Quay builds are amd64-only and haven't been especially reliable.  Use GitHub Actions to build both amd64 and arm64 containers for the main branch and for tags, and push them to Quay.  Continue building but not pushing containers on PR.  Requires the `QUAY_AUTH` repo secret to be set to a Docker credential.
Disable optimization in non-amd64 container builds to prevent the build job from timing out.
The build-container action doesn't cache build artifacts, unlike the Rust test job.  Skip the arm64 container in PRs to speed up CI.
Fixes https://github.com/coreos/coreos-installer/issues/793.

workflows: build and push container from GitHub Actions

---

src/blockdev.rs

On some Dell machines at least, something (UEFI firmware?) creates a
`Dell` directory in the `EFI` dir. This throws off our logic here which
expects only a single vendor dir.
Let's tweak the logic so that we only consider a "vendor dir" a
directory which has a `grub.cfg`.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/1116

blockdev: rework EFI vendor dir checking

---

src/live/mod.rs
src/source.rs
src/util.rs
tests/images/customize.sh
tests/images/dev-initrd.sh
tests/images/iso-ignition.sh
tests/images/iso-kargs.sh
tests/images/iso-network.sh
tests/images/unsupported.sh

Rust ignores `SIGPIPE` by default, which causes verbose failures when our output is piped to a program that exits.  In simple reporting and debugging commands where there's no need to clean up after execution, avoid this by resetting the `SIGPIPE` handler to `SIG_DFL`.
In the image tests, if `grep -q` exits while the writer has more data to write, the writer will die on `SIGPIPE` or otherwise exit nonzero, and then the test will fail because we set `-o pipefail`.  Use `grep > /dev/null` instead.  Fixes intermittent failures in CI.

Silence some errors when output is closed; fix tests not to do that

---

Cargo.lock
Cargo.toml
docs/cmd/download.md
docs/cmd/install.md
docs/cmd/iso.md
docs/cmd/list-stream.md
docs/cmd/pxe.md
src/bin/rdcore/cmdline.rs
src/bin/rdcore/main.rs
src/cmdline.rs
src/main.rs
src/miniso.rs
src/osmet/file.rs

clap 3 drops `...` from the help text for arguments that can be repeated, and expects applications to make repeatability clear from the arg description: https://github.com/clap-rs/clap/issues/1571#issuecomment-541313239.  I'm not sure of a good way to do that, so we're currently leaving repeatable arguments implicit.

Replace structopt with clap 3.1

---

README.md

Quay no longer performs the container build, so the build status badge isn't useful.  Replace it with a static badge that just says ![Container image](https://img.shields.io/badge/container-quay.io-blue)

README: replace container badge

---

src/blockdev.rs

`blkid` usage may help with https://github.com/coreos/fedora-coreos-tracker/issues/1105 , as it returns proper `LABEL` when `lsblk` doesn't

blockdev: use blkid instead of lsblk for querying all filesystems

---

Cargo.lock
Cargo.toml

Major changes:
- Add aarch64 support to container image
- Add generated manpages
Minor changes:
- Silence error from reporting commands like `iso ignition show` and `pxe ignition unwrap` if output pipe is closed
- docs: Document `dest-device` config file field
- docs: Document `iso/pxe customize` commands
- docs: Drop documentation of pre/post installation hooks
- bind-boot: Fix EFI vendor directory detection
- verify-unique-fs-label: use `blkid` instead of `lsblk` to make filesystem label querying more reliable
- Delete legacy aliases for `osmet` and `minimal-iso` pack commands used by coreos-assembler
- Require Rust ≥ 1.56.0
- Migrate from `structopt` to `clap` 3
- Add `clap_mangen` dependency
- Drop `openat-ext` dependency
- Remove Windows binaries …

cargo: coreos-installer release 0.14.0

---

.github/ISSUE_TEMPLATE/release-checklist.md

Fixes a1569d3 ("github/release-checklist: Remove Windows binaries from
vendored sources").

templates/release-checklist: fix path to winapi vendor dir

---

.github/workflows/rpm.yml

Recent git became more strict wrt git repos in parent dirs owned by
other users. This broke us likely due to the container workdir being a
volume mount. We need to explicitly mark the repo as safe.
Interestingly, the checkout action also does this but only temporarily
for itself.
For more information, see:
https://github.com/actions/checkout/issues/760

ci: mark git checkout as safe

---

Cargo.toml

It's odd to have s390x deps be listed after `dev-dependencies`. Have it
be just after `dependencies` instead since it's the same kind.

Cargo.toml: move s390x-specific deps near others

---

.github/workflows/rust.yml

Keep CI usable even though the s390x jobs are failing (https://github.com/coreos/coreos-installer/issues/872).
If this lands, I'll also mark the s390x jobs as non-required.

workflows: disable fail-fast on Rust jobs

---

docs/iso-embed-ignition.md

Current OSes no longer include the `coreiso+` header, and rely on coreos-installer parsing the ISO9660 metadata instead.  Also, the cpio archive is xz-compressed these days, and has been in a separate file since the feature first shipped.

docs: drop `coreiso+` header from ISO Ignition embed docs

---

.github/workflows/rust.yml

For now, shell out to git commands instead.
Fixes https://github.com/coreos/coreos-installer/issues/872.  Works around https://github.com/rust-lang/cargo/issues/10583.

workflows: disable cargo bundled libgit to avoid s390x OOM

---

src/install.rs

If `-p` is specified and `/boot/coreos/platforms.json` exists, look up the specified platform and the `metal` platform in that file.  Remove any metal-specific kernel arguments or GRUB commands specified there, and inject any kargs/commands for the new platform.  This allows us to apply a platform-specific console configuration at install time.
Set the platform before performing kargs modification to allow the latter to change a platform-specific default console.
When installing via `coreos.inst` kargs, persist any `console=` kargs to the destination system, as suggested in https://github.com/coreos/fedora-coreos-tracker/issues/567#issuecomment-901801590.

install: make platform-specific bootloader changes when `-p` specified

---

Cargo.lock

There are a lot of deprecations, but upstream has silenced the corresponding warnings while working through the mechanics of the transition.  Ignore them for now; we might end up waiting until 4.0 to update APIs.

cargo: update clap to 3.2.5

---

.github/ISSUE_TEMPLATE/release-checklist.md

We've gained some additional Windows-specific dependencies, and `vcpkg` also has compiled libraries for Darwin and iOS.  Our vendor tarball should never need to include compiled static libs, so delete them all.

templates/release-checklist: delete all `.a` files from vendor dir

---

Dockerfile

Container builds have been failing due to the same issue as in #872.  For now, shell out to git commands instead.

Dockerfile: disable cargo bundled libgit to avoid aarch64 OOM

---

Cargo.toml

See https://github.com/cgwalters/cargo-vendor-filterer
This project also only targets CoreOS/Linux so we don't need
any other platform dependencies.  Most notably this obsoletes
the manual step to strip all the large prebuilt static `.a` files
for the windows crates.
```
$ du -sh vendor-filtered vendor
54M     vendor-filtered
135M    vendor
```
(And that's after the `find vendor -name '*.a' -delete`)
Checklist update in https://github.com/coreos/repo-templates/pull/4.

Configure `cargo vendor-filterer`

---

.github/workflows/env-setup

We install `qemu-s390x-static` by downloading and extracting a single Fedora binary package into an Ubuntu system, without respecting package dependencies.  As a consequence, when `qemu-user-static` was converted to a metapackage for https://github.com/coreos/fedora-coreos-tracker/issues/1088, we stopped actually installing the emulator.  Use the correct subpackage instead.
I've opted not to revert c3b3d49d4195c6016d3bececbf1c8012f21bc020 for now.  By leaving fail-fast disabled, we avoid wasting resources for successful jobs when we rerun failed ones after a flake, and make it easier to get CI signal if the s390x jobs break again in the future.  The downside is some CI resource waste when a PR has correlated job failures.

workflows: fix installation of `qemu-s390x-static`

---

docs/release-notes.md

Copied from GitHub releases, with draft notes for unreleased changes.
Drop the crate/vendor hashes, since otherwise there's a circular dependency; we don't know them until after we tag and build.

docs: add release notes

---

src/bin/rdcore/rootmap.rs

This combinator style avoids an unnecessary `Vec` allocation and
also the implicit panic possible on array indexing.

rootmap: Use `split_once`

---

src/bin/rdcore/rootmap.rs

I happened to be have this code open for an unrelated reason
and noticed that this open-coded loop can be replaced by a `collect`.
We can already generate hashmap entries from a `(key, value)` tuple,
and `collect()` also knows how to generate a `Result<T>` which
it will know to do from type inference.

rdcore: Use collect instead of manual loop

---

Cargo.toml

The idea of the explicit ranges is to exactly replicate the ranges that Cargo would allow if a bare version were specified, while convincing Dependabot not to bump the minimum version.  For major versions > 0, Cargo would allow every minor up to the next major, so we should do that too.
See discussion [here](https://src.fedoraproject.org/rpms/rust-coreos-installer/pull-request/40).

cargo: update version ranges for post-1.x deps

---

src/bin/rdcore/rootmap.rs
src/blockdev.rs

Systems where some filesystems were luks2-encrypted with 'integrity' option have special
crypt-integrity devices:
```
NAME                 FSTYPE      FSVER LABEL        UUID
vda
|-vda3               crypto_LUKS 2     crypt_bootfs f55add4a-1351-4699-9e61-32f33a68a031
| `-crypt_bootfs_dif
|   `-crypt_bootfs   ext4        1.0   boot         3d4ed0e4-40ba-4930-99ff-35d2be907ec3
|-vda4               crypto_LUKS 2     crypt_rootfs 7c5341bf-9616-4ce1-90dc-111b03379799
| `-crypt_rootfs_dif
|   `-crypt_rootfs   xfs               root         d0bc5f93-f2ac-42f3-8b16-27b0794266c5
```
So to get 'uuid' of such devices, we have to recursively go to the underlying block device.
crypt-integrity devices on the other hand should be skipped during 'rdcore rootmap'.

rootmap: handle filesystems with LUKS integrity

---

docs/release-notes.md
src/bin/rdcore/cmdline.rs
src/bin/rdcore/kargs.rs

This allows such invocation to be possible:
```
rdcore zipl --append-karg=ignition.firstboot --append-karg=lockdown=confidentiality --secex-mode=enforce --boot-mount=/boot
```
Required for:
https://github.com/coreos/coreos-assembler/pull/3002

rdcore: zipl: add support for multiple '--append-karg'

---

docs/release-notes.md
src/io/bls.rs
src/s390x/zipl.rs

This brings support for recent move from `LUKS2` to `dm-verity` introduced by https://github.com/coreos/coreos-assembler/pull/3039.

s390x: don't fail if luks isn't used

---

docs/release-notes.md
src/bin/rdcore/cmdline.rs

We need to keep providing the old alias here to make the transition
easier in cosa.
Note the semantics are a little different (before, this was an
`Option<String>`, now it's an `Option<Vec<String>>`), but it still works
for what we need here.

rdcore/zipl: alias old `--kargs` to new `--append-karg`

---

.github/workflows/rust.yml
Cargo.toml
Makefile
data/example-config.yaml
docs/_config-file.sh
docs/customizing-install.md
docs/release-notes.md
src/cmdline/doc.rs
src/cmdline/mod.rs
src/main.rs

If the `docgen` feature is enabled, add a subcommand to walk the `InstallConfig` struct and generate an example config file.  Use it to regenerate `customizing-install.md` and a new `example-config.yaml` when rebuilding docs.
Install `example-config.yaml` in `/usr/share/coreos-installer` for use by cosa, which can automatically add feature flags to the live image for each config option supported by the installer.

Generate and install example install config file

---

docs/release-notes.md
src/blockdev.rs

`install --save-partindex` and `install --save-partlabel` both search the GPT for the specified partitions. While MBR doesn't have partition labels, it does have partition indexes. Users might try to use `--save-partindex` with an MBR disk, resulting in data loss when coreos-installer doesn't notice the specified partitions.
To address this, we'll need to detect saved MBR partitions and convert them to GPT partitions in the output. As a first step, if `--save-partindex` is specified and the disk has an MBR but no GPT, fail install to avoid data loss.
Fixes https://github.com/coreos/coreos-installer/issues/816.

blockdev: fail `install --save-partindex` on MBR-formatted disks 

---

docs/release-notes.md
src/bin/rdcore/cmdline.rs
src/bin/rdcore/kargs.rs
src/install.rs
src/s390x/zipl.rs

In SE case we append `luks2` keys to original `initrd`. It may be also useful to append some more user-defined files to `sdboot` image.

rdcore: add '--append-file' for 'zipl' subcommand

---

docs/release-notes.md

https://github.com/coreos/coreos-installer/issues/978
Working on releasing coreos-installer 0.16.0

docs/release-notes: update for new version

---

docs/release-notes.md
src/osmet/unpacker.rs

Debug builds on Rust 1.64+ were seeing a substantial performance hit in osmet unpack, causing the `kola testiso` `pxe-offline-install` scenario to time out.  This is due to an apparent Rust performance regression when `BufReader`'s buffer is larger than the blocks returned by the inner reader, if the code is built without optimization.  In our case, osmet's `write_unpacked_image()` produces data in 8 KiB chunks, which are passed verbatim through the pipe to the 256 KiB `PeekReader` in `write_image()`.
For now, work around this by having osmet consolidate writes through a 256 KiB `BufWriter`.  The extra buffer is harmless, but once the affected Rust versions are no longer being used for development, it probably makes sense to drop this code.
xref …

osmet: avoid install performance regression in debug mode on Rust 1.64+

---

Cargo.lock
Cargo.toml
docs/release-notes.md
src/s390x/fba.rs

`default-features = false` was always redundant; drop it.

cargo: bump mbrman to 0.5.0

---

.github/workflows/rpm.yml
.github/workflows/rust.yml

s390x tests are expensive, and when we're merging a lot of Dependabot PRs, CI can get backed up running redundant tests on main.  We don't need to continue running tests that have been superseded by new code, either in main or in a PR branch, so add concurrency configuration to cancel them.

workflows: cancel superseded Rust and RPM jobs

---

src/blockdev.rs
src/cmdline/doc.rs
src/install.rs
src/miniso.rs

Just a drive by commit; I was looking at the code and I think inline format is nicer.

Use inline `format!` in a few places

---

.github/workflows/rpm.yml
.github/workflows/rust.yml

Fixes [deprecation warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for Node.js 12.

workflows: update actions to current major versions

---

docs/release-notes.md
src/install.rs

Normally we want to check the install image before starting to do I/O to the destination disk.  However, low-level formatting an ECKD DASD can take a long time, and if we initiate download of the install image first, the TCP connection will sit without any bytes being read and may eventually time out.  Avoid this by doing the low-level format before starting the fetch.
Fixes https://github.com/coreos/coreos-installer/issues/431.

install: low-level format ECKD DASD before initiating fetch

---

.github/workflows/rpm.yml
Cargo.lock
Cargo.toml
docs/release-notes.md

nmstate 2.2.0 split its functionality into multiple features, which allows us to reduce the set of dependencies we pull in.  nmstate 2.2.3 restored the MSRV to 1.58.0 so we can use it.
xref https://github.com/coreos/coreos-installer/issues/1032#issuecomment-1296979952

cargo: bump to nmstate 2.2.3 with only `gen_conf` feature

---

.github/workflows/rpm.yml

We can stop using `updates-testing` now that nmstate 2.2.3 is stable in Fedora 37.

Revert "workflows: temporarily enable updates-testing repo for RPM test"

---

docs/release-notes.md
src/blockdev.rs

By default, `blkid` will return cached data, which we don't want because
it might be stale. We need to use`-p` to make sure it directly probes
the block devices and bypasses the cache.
With `-p`, `blkid` requires passing the devices directly. Call it once
to gather the list of devices (we trust the cache enough for this) and
then again with `-p`.
We originally used `lsblk` here which uses the udev database, but this
was changed in https://github.com/coreos/coreos-installer/pull/813
because it failed to return the filesystem label in some instances. It
might be worth revisiting this at some point and find out if we were
just missing a `udevadm settle` somewhere.
See also: https://github.com/coreos/fedora-coreos-config/pull/2181#issuecomment-1397386896

blockdev: use `-p` when calling `blkid`

---

src/blockdev.rs

Lazily compile and cache the regexp we use to parse lsblk output just once - doing it on every line of the output is a bit wasteful. (Noticed this when copy-pasting the code into bootc)

blockdev: Only compile regex once

---

docs/release-notes.md

#1117 added support but it wasn't noted at the time.

docs/release-notes: note support for Ignition spec 3.4.0

---

Cargo.toml
docs/release-notes.md

We no longer need to support older Rust versions.
Use the new `dep:` syntax to avoid creating an implicit `clap_mangen` feature.

cargo: bump MSRV to 1.66.0

---

.cci.jenkinsfile

The new `kola testiso` code will test NM keyfiles by default, so there's no need to do a separate run anymore.
While we're here, just accept the new default list of tests from `kola testiso` by only denylisting the `iso-as-disk` and `iso-live-login` tests and otherwise not overriding the tests to run.
This will run more tests than before. We'll likely cut down tests we consider redundant soon, but that should be transparent to this code.

ci: migrate to new kolaTestIso()

---

.cci.jenkinsfile

Previously, there was a separate `skipMetal4k` flag that governed 4Kn tests, but now those are gated by `skipUEFI`.
Fixes #1120.

ci: enable UEFI tests to get 4Kn tests

---

docs/release-notes.md
src/live/mod.rs

When installing with `coreos.inst` kargs, Ignition kargs are not normally used.  However, when a customized PXE initrd embeds a live Ignition config, Ignition kargs are required.  Warn the user in this case.
For https://github.com/coreos/fedora-coreos-tracker/issues/1426.

live: warn when `pxe customize` output requires Ignition kargs

---

.cci.jenkinsfile
tests/images.sh

In general, we want to test the binary built in the source tree and raise an error if that binary is missing.  Historically we failed to notice this case and fell back to testing the installed binary, if present. CoreOS CI took advantage of this.
Fail if the coreos-installer binary isn't in the source tree, unless `COREOS_INSTALLER_TEST_INSTALLED_BINARY` is set, in which case print a warning and continue.
Also have CI delete the OS copy of coreos-installer before overwriting it with rsync.  This ensures we don't test the wrong thing if the OS copy is elsewhere in `PATH`, or if coreos-installer is missing from the install tree.
Followup to https://github.com/coreos/coreos-installer/pull/999#discussion_r1004688601.

tests/images: only test installed binary if env var set

---

Cargo.toml
docs/release-notes.md

ignition-config 0.2 doesn't support Ignition config spec 3.4.0. coreos-installer itself doesn't care, but it'd be confusing if some coreos-installer 0.17.0 binaries supported 3.4.0 configs and some didn't. Explicitly require ignition-config 0.3 to warn downstreams.

cargo: require ignition-config 0.3

---

docs/release-notes.md
src/osmet/unpacker.rs

The Rust regression was fixed by https://github.com/rust-lang/rust/pull/102760, which is in Rust 1.66+. Our MSRV is 1.66.0, so we can drop this.
This reverts commit 1ccb9b091afddca29fe64135882a48b7295e6ab8.

Revert "osmet: avoid install performance regression in debug mode on Rust 1.64+"

---

data/example-config.yaml
docs/cmd/download.md
docs/cmd/install.md
docs/customizing-install.md
docs/release-notes.md
man/coreos-installer-download.8
man/coreos-installer-install.8
src/cmdline/install.rs
src/cmdline/mod.rs

It permits the signature to be missing, but does not permit the signature to be invalid or to be made with an unknown key.
Fixes https://github.com/coreos/coreos-installer/issues/1141.

cmdline: clarify description of `--insecure`

---

Cargo.toml

This fixes the problem described in the comment.

build-sys: Use new `tier = 2` for cargo-vendor-filterer

---

.github/workflows/rust.yml

It can do a better job than our manual hack.
Also enable dependency caching on x86_64 to conserve CI resources.
Also do some unrelated small cleanups.

workflows: use Swatinem/rust-cache to cache Rust dependencies

---

systemd/coreos-installer-generator

Fix ShellCheck warning:
```
In ./systemd/coreos-installer-generator line 13:
cmdline=( $(</proc/cmdline) )
^---------------^ SC2207 (warning): Prefer mapfile or read -a to split command output (or quote to avoid splitting).
```
See: https://github.com/coreos/coreos-installer/pull/999
See: https://bugzilla.redhat.com/show_bug.cgi?id=1989551

systemd/coreos-installer-generator: Properly read cmdline

---

.github/workflows/rust.yml
src/blockdev.rs
src/download.rs
src/io/peek.rs

By default, `cargo clippy` does not check tests.  Run it with `--all-targets` to fix this.  For consistency, add the same option to `cargo build` and `cargo test`.

workflows: run clippy on tests

---

docs/release-notes.md
src/install.rs

If the user accidentally specifies a URL to an HTML page instead of an Ignition config, detect that before we install.
Fixes https://github.com/coreos/coreos-installer/issues/1231.

install: verify that Ignition config is valid JSON

---

docs/release-notes.md
src/blockdev.rs

Boot VM failed with following logs, the reproduce rate is 2/4.
```
systemd[1]: Starting CoreOS Ensure Unique Boot Filesystem...
rdcore[1252]: blkid: error: /dev/sr0: No such file or directory
rdcore[1252]: Error: "blkid" "-p" "/dev/sdb1" "/dev/sr0"
"/dev/sda4" "/dev/sda2" "/dev/sda3" "/dev/sda1" failed with exit
status: 2
systemd[1]: coreos-ignition-unique-boot.service: Main process
exited, code=exited, status=1/FAILURE
coreos-ignition-unique-boot.service: Failed with result 'exit-code'.
Failed to start CoreOS Ensure Unique Boot Filesystem.
systemd[1]: coreos-ignition-unique-boot.service: Triggering
OnFailure= dependencies.
```
Seems `blkid` collecting old devices from cache which no longer
exist, should run with a clean cache before gathering the list of
devices.
Fixes …

verify-unique-fs-label: Run `blkid` with a clean cache to avoid stale devices

---

.cci.jenkinsfile

This reverts commit 2247ffe1f8f64317da570a8d230bfc1ff782164b.
This shouldn't be necessary now with the workaround built into cosa:
https://github.com/coreos/coreos-assembler/pull/3625

Revert "ci: run cosa unprivileged temporarily for virtiofs bug"

---

docs/release-notes.md
src/bin/rdcore/main.rs
src/bin/rdcore/rootmap.rs

rdcore: Juggle physical root versus deployment root
This is prep for supporting composefs, where the physical root
is distinct from the deployment root.  Specifically for the LUKS
case, we can find `/etc/crypttab` only in the deployment root.
Otherwise, we suffix the passed path (usually `/sysroot`) that
was mounted in the initramfs with `/sysroot` to find the physical
root.
xref https://github.com/ostreedev/ostree/issues/2867

rdcore: Juggle physical root versus deployment root

---

data/example-config.yaml
docs/cmd/install.md
docs/customizing-install.md
docs/release-notes.md
man/coreos-installer-install.8
scripts/coreos-installer-service
src/cmdline/install.rs
src/install.rs
src/s390x/mod.rs
src/s390x/zipl.rs
systemd/coreos-installer-post.target
systemd/coreos-installer-reboot.service
systemd/coreos-installer-secure-ipl-reboot.service

Implements proposal from: https://github.com/coreos/enhancements/pull/10

s390x: add zVM Secure IPL support

---

.packit.yaml

This config is setup to target downstream job automation in pagure.
This change is dependent on https://src.fedoraproject.org/rpms/rust-coreos-installer/pull-request/57 landing, as it takes out the gymnastics associated with patch management on a normalized cargo.toml.
As it's difficult to test Packit locally, we will need to see the results as an experiment and at release time, capture any issues, and resolve / iterate.

packit: add initial support

---

.packit.yaml
docs/release-notes.md

The `changelog-entry` field needs a value which creates an output of the entry you want in your changelog.
fixes #1357

packit: fix changelog-entry

---

docs/release-notes.md
src/install.rs

Upstream we are starting to use grub configs that are partially baked into bootupd [1] and partially baked into the image via the OS vendor (in our case a grub2/30_console.cfg file [2]). Let's look first to see if grub2/30_console.cfg exists when trying to write new console settings before falling back to grub2/grub.cfg.
[1] https://github.com/coreos/bootupd/pull/543
[2] https://github.com/coreos/fedora-coreos-config/pull/2769

install: support grub2/30_console.cfg for console replacement

---

docs/release-notes.md
src/s390x/zipl.rs

There is no need to copy `boot/loader/entries` folder and to create temporary `zipl.conf` , instead we could parse bls config and tell `zipl` which image and disk to use. This also fixes an issue when images comes with `bootprefix`.
Issue: https://github.com/coreos/fedora-coreos-tracker/issues/1667

s390x: call zipl using exact kernel, ramdisk and cmdline

---

docs/release-notes.md
src/install.rs

In https://github.com/coreos/fedora-coreos-tracker/issues/1671 we decided to use a non-static grub file for console configuration named console.cfg.

install: use console.cfg rather than 30_console.cfg

---

Cargo.lock
Cargo.toml
docs/release-notes.md

https://github.com/coreos/coreos-installer/issues/1425

Pre release 0.21.0

---

.packit.yaml
docs/release-notes.md

After the latest release we noticed that f40 was not included, this is because its not stable yet. which means that it would be ignored by packit.

packit: update dist_git_branches to target fedora-all

---

docs/release-notes.md
src/bin/rdcore/rootmap.rs
src/blockdev.rs

In the multipath + LUKS case, `get_luks_uuid()` would incorrectly
skip over the multipath partition containing the LUKS header because
`is_dm_device()` returned true. The code eventually errors out when it
gets to the disks backing the multipath device.
The `is_dm_device()` check was added as part of 69b706d ("rootmap:
handle filesystems with LUKS integrity") to correctly handle the LUKS
integrity case in the Secure Execution path. There, the device right
under the LUKS device is another crypt device mapper device used for
integrity that we need to skip over.
Instead of generically checking for a device mapper target, check
specifically that it's a LUKS integrity target before deciding to skip.
Part of: https://github.com/coreos/fedora-coreos-tracker/issues/1728

rootmap: fix multipath + LUKS case

---

.packit.yaml
docs/release-notes.md

Declare downstream_package_name for each package; i.e fedora and centos.

packit: downstream_package_name is not inherited by packages

---

.packit.yaml
docs/release-notes.md

While releasing coreos-installer, we found that the current CentOS packaging did not introduce enough benefit to outweigh the process change required to keep other repos consistent. We will revisit once additional support is added for running builds/tests/ticketing.
Ref: https://github.com/packit/packit-service/issues/2106

packit: drop CentOS packaging

---

docs/release-notes.md
src/blockdev.rs

- OSBuild does not allow udev rules in loop devices, for this reason can not rely on labels on the partitions to create the osmet image, we
need to skip this part and pass only the fstype
for the it to be mounted.

Use  blkid instead of lsblk to get disk info when udev is not present

---

docs/release-notes.md
src/s390x/zipl.rs

Since s390-tools commit [f4cf4ae6ebb1](https://github.com/ibm-s390-linux/s390-tools/commit/195579cf0bcff320ed9ebe2cab6b59c9cc817f6e)  (Remove genprotimg-C and switch to genprotimg-Rust implementation) 
FCCOS/RHCOS may come with symlink to `pvimg create`. 
New `pvimg` made some cmdline options obsolete (`-V`) and by default doesn't overwrite the output image (`sdboot`), which leads to an issue https://github.com/openshift/os/issues/1731.
For now keep the call to `genprotomg`, even if it's symlink, but let's:
- remove the `sdboot` before generating new one
- use long cmdline options supported by both tool.

s390x: prepare for the upcoming 'pvimg' tool replacing 'genprotimg'

---

docs/release-notes.md
src/download.rs

Prior to v0.24.1 the output when processing a stream of disk image input the output would write with 1 decimal place of precision:
```
Read disk 118.2 MiB/2.6 GiB (4%)
Read disk 157.0 MiB/2.6 GiB (5%)
Read disk 300.1 MiB/2.6 GiB (11%)
Read disk 450.6 MiB/2.6 GiB (16%)
Read disk 515.2 MiB/2.6 GiB (19%)
```
After v0.24.1 it has many decimal places of precision:
```
Read disk 138.2265625 MiB/2.59765625 GiB (5%)
Read disk 265.6722106933594 MiB/2.59765625 GiB (9%)
Read disk 399.67578125 MiB/2.59765625 GiB (15%)
Read disk 519.40625 MiB/2.59765625 GiB (19%)
Read disk 597.5625 MiB/2.59765625 GiB (22%)
```
This is likely due to 68198d0. Let's get back the previous formatting.

download: format byte unit with 1 decimal place precision

---

Cargo.toml
docs/release-notes.md
src/bin/rdcore/rootmap.rs
src/install.rs
src/io/initrd.rs
src/io/limit.rs
src/iso9660.rs
src/live/embed.rs
src/osmet/unpacker.rs

- To ensure multipath continues working even if a path fails, the WWID must be specified both as a
kernel argument and in /etc/multipath/wwids.
Without these, multipath may fail to detect
devices when paths go down, leading to device
mapping issues.
- This PR adds mpath.wwid kernel argument needed for the installer.

OCPBUGS-56597: Fix multipath configuration
